// GİBİ — "Yedek Anahtar" (hayran bölümü)
// Bu dosya bölümün TEK kaynağıdır: senaryo metni (SENARYO.md), seslendirme
// listesi ve three.js animasyonu buradan üretilir.
//
// Koordinatlar her setin kendi yerel düzlemindedir: x sağa, z kameraya doğru.
// Bir karakterin yüzü yaw=0'da +z yönüne (kameraya) bakar; yaw=90 → +x.

export const meta = {
  series: 'GİBİ',
  title: 'Yedek Anahtar',
  tag: 'Hayran Bölümü',
  logline:
    'Yılmaz, evinin yedek anahtarını büyük bir törenle İlkkan\'a verir; ' +
    'ama "acil durum"un tanımı üzerine kurulan kurallar ertesi sabah ' +
    'herkesi kapının dışında bırakır.',
};

export const cast = {
  yil: { name: 'YILMAZ', voice: { pitch: -1.5, speed: 1.06, noise: 0.62 } },
  ilk: { name: 'İLKKAN', voice: { pitch: 1.2, speed: 0.96, noise: 0.7 } },
  nec: { name: 'NECMİ BEY', voice: { pitch: 3.2, speed: 1.12, noise: 0.75 } },
  rem: { name: 'KAPICI REMZİ', voice: { pitch: -3.6, speed: 1.0, noise: 0.6 } },
  hus: { name: 'ÇİLİNGİR HÜSNÜ', voice: { pitch: -2.4, speed: 0.92, noise: 0.68 } },
};

// --- yardımcılar -----------------------------------------------------------
const say = (who) => (text, o = {}) => ({ type: 'say', who, text, ...o });
const Y = say('yil');
const I = say('ilk');
const N = say('nec');
const R = say('rem');
const H = say('hus');
const BOTH = (text, o = {}) => ({ type: 'say', who: ['yil', 'ilk'], text, p: 'birlikte', ...o });
const act = (text, ops = [], o = {}) => ({ type: 'act', text, ops, ...o });
const card = (text, dur = 2.6, o = {}) => ({ type: 'card', text, dur, ...o });

// --- sahneler --------------------------------------------------------------
export const scenes = [
  // ======================================================================
  {
    id: 'acilis',
    label: 'SOĞUK AÇILIŞ',
    heading: 'İÇ. İLKKAN\'IN EVİ – SALON – AKŞAM',
    set: 'A',
    time: 'night',
    ambience: 'room',
    cast: {
      ilk: { pos: [0.6, -2.05], yaw: 0, sit: true, look: [4.2, 1.1, -1.2] },
      yil: { pos: [-5.4, 0.6], yaw: 90, hold: 'gift' },
    },
    beats: [
      act('İlkkan kanepede oturmuş, televizyonda bir belgesel izliyor. Kapı üç kez, ölçülü bir ritimle çalınır.', [
        { wait: 1.2 }, { sfx: 'knock' }, { wait: 1.0 }, { look: 'ilk', at: [-4.5, 1.4, 0.6] }, { wait: 0.6 },
      ], { cam: 'wide' }),
      act('İlkkan söylenerek kalkar, kapıya gidip açar. Kapıda elinde kurdeleli küçük bir kutuyla Yılmaz durmaktadır.', [
        { stand: 'ilk' }, { mv: 'ilk', to: [-3.5, 0.9] }, { face: 'ilk', at: -90 },
        { sfx: 'doorOpen' }, { door: 'A', v: 1, par: true },
        { mv: 'yil', to: [-3.9, 0.45], sp: 1.0 },
        { mv: 'ilk', to: [-2.1, 0.95], sp: 0.9, par: true },
        { face: 'yil', at: 'ilk' }, { face: 'ilk', at: 'yil', par: true },
      ], { cam: 'wide', look: 'ilk' }),
      Y('İlkkan, iyi akşamlar. Müsait misin?', { e: 'serious' }),
      I('Değilim ama gir.', { e: 'tired', do: [{ door: 'A', v: 0, time: 1.2 }, { sfx: 'doorClose', par: true }] }),
      act('Yılmaz içeri girer, kapı kapanır. Kutuyu iki eliyle, bir madalya verir gibi uzatır.', [
        { mv: 'yil', to: [-3.1, 0.4], sp: 0.8 }, { face: 'yil', at: 'ilk' }, { g: 'yil', v: 'present' },
      ]),
      Y('Bu senin için.', { g: 'present' }),
      I('Ne bu? Doğum günüm değil.', { e: 'surprised' }),
      Y('Doğum günü hediyesi değil. Sorumluluk hediyesi.', { e: 'serious', g: 'raise' }),
      act('İlkkan kutuyu alır, kurdeleyi çeker. İçinden tek bir anahtar çıkar.', [
        { hold: 'yil', v: null }, { hold: 'ilk', v: 'gift', par: true }, { wait: 0.8 },
        { hold: 'ilk', v: 'key' }, { g: 'ilk', v: 'inspect' },
      ], { cam: 'cu:ilk' }),
      I('Anahtar?', { e: 'surprised' }),
      Y('Evimin yedek anahtarı. Uzun süre düşündüm. Hayatımda buna layık tek insan sensin.', { e: 'serious', g: 'explain' }),
      I('Sağ ol Yılmaz. Duygulandım şimdi.', { e: 'happy', g: 'heart' }),
      Y('Duygulanma. Duygulanan insan anahtar kaybeder.', { e: 'serious', g: 'stop' }),
      I('Tamam. Duygulanmadım.', { e: 'neutral' }),
      Y('Bu anahtar sadece acil durumda kullanılacak.', { g: 'raise' }),
      I('Tabii ki. Acil durumda.', { g: 'nod' }),
      Y('Acil durum ne, biliyor musun?', { e: 'smug' }),
      I('Biliyorum Yılmaz. Acil... acil olan durum.', { g: 'shrug' }),
      Y('İşte bu yüzden konuşmamız lazım. Otur.', { e: 'serious', g: 'point' }),
      I('Benim evim burası.', { e: 'angry', g: 'explain' }),
      Y('O yüzden rahat otur.', { e: 'neutral' }),
      act('İkisi kanepeye oturur. Yılmaz parmaklarıyla saymaya hazırlanır.', [
        { mv: 'ilk', to: [0.6, -1.55] }, { mv: 'yil', to: [-0.5, -1.55], par: true },
        { sit: 'ilk', at: [0.6, -2.05], yaw: 0 }, { sit: 'yil', at: [-0.5, -2.05], yaw: 0, par: true },
        { look: 'ilk', at: 'yil' }, { look: 'yil', at: 'ilk', par: true },
      ], { cam: 'wide' }),
      Y('Acil durum üç tanedir. Bir: yangın.', { g: 'count1' }),
      I('Mantıklı.', { g: 'nod' }),
      Y('İki: sel.', { g: 'count2' }),
      I('Yılmaz, sen beşinci kattasın.', { e: 'surprised', g: 'explain' }),
      Y('Sel aşağıdan gelmez İlkkan. Yukarıdaki komşunun çamaşır makinesi patlar, sel yukarıdan gelir.', { e: 'serious', g: 'explain' }),
      I('Peki. Üç?', { e: 'tired' }),
      Y('Üç: Ben "acil" dersem.', { g: 'count3', e: 'smug' }),
      I('Bu nasıl madde?', { e: 'angry', g: 'shrug' }),
      Y('En önemli madde. Diğer ikisi de aslında bunun içinde.', { g: 'explain' }),
      I('Yani yangın çıkınca da sen bana "acil" diyeceksin.', { g: 'point' }),
      Y('Yangın çıkınca kimse kimseye bir şey demez. Herkes kaçar.', { e: 'serious' }),
      I('O zaman ben yangını nereden bileceğim?', { g: 'shrug' }),
      Y('Haberlerden.', { e: 'neutral', pause: 0.4 }),
      I('Yılmaz. Sen beni arayıp "acil" dersen, ben gelirim, kapını çalarım, sen açarsın. Anahtara ne gerek var?', { g: 'explain', e: 'angry' }),
      Y('Ben açamayacak durumdaysam?', { e: 'smug' }),
      I('Neden açamayacaksın?'),
      Y('Çünkü acil durum var.'),
      I('Ne acil durumu?', { e: 'angry', g: 'shrug' }),
      Y('Açamadığım için acil durum.', { e: 'serious' }),
      I('Yılmaz, bu bir döngü.', { g: 'facepalm' }),
      Y('Hayat bir döngü İlkkan.', { e: 'serious', g: 'raise', cam: 'cu:yil' }),
      I('Tamam. Anladım. Acil durumda kullanırım.', { e: 'tired' }),
      Y('Bir de... kaybetme.', { g: 'point' }),
      I('Kaybetmem.'),
      Y('Kaybedersen bu bir acil durum olur.', { e: 'serious' }),
      I('O zaman ne yapacağım?', { e: 'surprised' }),
      Y('Yedek anahtarı kullanırsın.', { e: 'neutral' }),
      I('Yedek anahtar bu!', { e: 'angry', g: 'shake_key' }),
      Y('Yedeğin yedeği evde. Çekmecede.', { e: 'smug' }),
      I('Yedeğin yedeği evdeyse, sen dışarıda kalınca onu nasıl alacaksın?', { g: 'explain' }),
      Y('Sana telefon edeceğim. Sen gelip yedekle açacaksın. Ben de içeri girip yedeğin yedeğini alacağım.', { g: 'explain' }),
      I('Neden?', { e: 'surprised' }),
      Y('Yedeksiz kalmamak için.', { e: 'serious' }),
      I('Yedek bende zaten!', { e: 'angry', g: 'flail' }),
      Y('Sen de acil durumda olabilirsin İlkkan. Hayat bu.', { e: 'sad', cam: 'cu:yil' }),
      act('Sessizlik. İlkkan anahtara, sonra Yılmaz\'a bakar.', [{ wait: 1.6 }], { cam: 'two' }),
      I('Peki ben bunu nereye koyayım?', { e: 'neutral' }),
      Y('Kalbine.', { e: 'happy', g: 'heart' }),
      I('Anahtarlığa takayım.', { e: 'tired' }),
      Y('Olur. Kalbin anahtarlığıysa.', { e: 'serious', cam: 'cu:yil', pause: 0.8 }),
    ],
  },
  // ======================================================================
  {
    id: 'jenerik',
    label: 'JENERİK',
    heading: 'JENERİK',
    title: true,
    beats: [{ type: 'title', dur: 6.5 }],
  },
  // ======================================================================
  {
    id: 'telefon',
    label: 'SAHNE 1',
    heading: 'İÇ. İLKKAN\'IN EVİ / YILMAZ\'IN EVİ – SABAH',
    set: 'A',
    time: 'morning',
    ambience: 'room',
    cast: {
      ilk: { pos: [0.6, -2.05], yaw: 0, sit: true, outfit: 'pajama', sleep: true },
      yil: { set: 'B', pos: [-0.5, -2.05], yaw: 0, sit: true, hold: 'tea' },
    },
    beats: [
      card('Ertesi sabah. 07.12', 2.4),
      act('İlkkan pijamalarıyla kanepede uyuyakalmış. Sehpadaki telefon çalar.', [
        { wait: 1.0 }, { sfx: 'phone' }, { wait: 2.2 }, { wake: 'ilk' }, { g: 'ilk', v: 'jump' },
        { pose: 'ilk', v: 'phone' }, { wait: 0.5 },
      ], { cam: 'wide' }),
      I('Alo?', { e: 'tired', p: 'uykulu' }),
      act('Yılmaz kendi evinde, kanepesinde. Bir elinde çay, öbüründe telefon. Son derece sakin.', [
        { pose: 'yil', v: 'phone' }, { wait: 1.2 },
      ], { cam: 'cu:yil' }),
      Y('İlkkan. Acil durum.', { e: 'serious' }),
      I('Ne oldu? Yangın mı?', { e: 'scared', g: 'jump', do: [{ stand: 'ilk' }] }),
      Y('Değil.', { e: 'neutral' }),
      I('Sel mi?', { e: 'scared' }),
      Y('Değil.'),
      I('...Üçüncü madde mi?', { e: 'surprised', pause: 0.3 }),
      Y('Üçüncü madde.', { e: 'serious', pause: 0.3 }),
      I('Geliyorum! Hiçbir şey yapma!', { e: 'scared', g: 'flail' }),
      Y('Zaten bir şey yapamıyorum. Acil durum o.', { e: 'sad' }),
      act('İlkkan telefonu kapatır, pijamalarıyla kapıya koşar ve çıkar. Kapı çarpar.', [
        { pose: 'ilk', v: null }, { mv: 'ilk', to: [-3.6, 0.6], sp: 3.2 },
        { door: 'A', v: 1, dur: 0.25 }, { sfx: 'doorOpen', par: true },
        { mv: 'ilk', to: [-5.6, 0.6], sp: 3.2 },
        { door: 'A', v: 0, dur: 0.2 }, { sfx: 'slam', par: true }, { wait: 0.8 },
      ], { cam: 'wide' }),
      act('Yılmaz, çayından bir yudum alır.', [{ pose: 'yil', v: null }, { g: 'yil', v: 'sip' }, { wait: 0.6 }], { cam: 'cu:yil' }),
    ],
  },
  // ======================================================================
  {
    id: 'plan',
    label: 'SAHNE 2',
    heading: 'İÇ. YILMAZ\'IN EVİ – SALON – SABAH',
    set: 'B',
    time: 'morning',
    ambience: 'room',
    list: 3,
    cast: {
      yil: { pos: [-0.5, -2.05], yaw: 0, sit: true, hold: 'tea' },
      ilk: { pos: [-5.5, 0.6], yaw: 90, outfit: 'pajama', hold: 'key' },
    },
    beats: [
      act('Kilit döner. İlkkan nefes nefese, pijamalarıyla içeri dalar. Yılmaz kanepede çayını içmektedir.', [
        { sfx: 'unlock' }, { wait: 0.6 }, { door: 'B', v: 1, dur: 0.35 }, { sfx: 'doorOpen', par: true },
        { mv: 'ilk', to: [-2.4, 0.5], sp: 2.6 }, { face: 'ilk', at: 'yil' },
        { look: 'yil', at: 'ilk', par: true },
      ], { cam: 'wide' }),
      I('Yılmaz! İyi misin?', { e: 'scared', g: 'flail' }),
      Y('Sessiz ol. Duyacak.', { e: 'serious', g: 'hush' }),
      I('Kim duyacak?', { e: 'surprised', p: 'fısıldayarak' }),
      Y('Necmi Bey.', { pause: 0.3 }),
      act('Yılmaz kalkar, kapıya gidip sessizce kapatır.', [
        { stand: 'yil' }, { hold: 'yil', v: null }, { mv: 'yil', to: [-3.7, 0.2], sp: 1.1 },
        { door: 'B', v: 0, dur: 0.9 }, { sfx: 'click', par: true },
        { mv: 'yil', to: [-3.1, 0.2], sp: 1 }, { face: 'yil', at: 'ilk' },
      ], { cam: 'wide' }),
      I('Komşun Necmi Bey mi?'),
      Y('Sekiz numara. Her sabah kapısının dürbününden bakıyor. Ben kapıyı açtığım an çıkıyor:', { g: 'explain' }),
      Y('"Yılmaz Bey, bir şey isteyeceğim."', { e: 'smug', g: 'raise', p: 'Necmi Bey\'i taklit ederek' }),
      I('Ne istiyor?'),
      Y('Her gün başka bir şey. Pazartesi şeker istedi. Salı matkap. Çarşamba internet şifremi istedi.', { g: 'count3' }),
      I('Verdin mi?'),
      Y('Verdim. Perşembe internetimi istedi.', { e: 'sad' }),
      I('İnternet verilir mi?', { e: 'surprised', g: 'shrug' }),
      Y('Modemi verdim İlkkan. Şu an evde internet yok.', { e: 'sad', cam: 'cu:yil' }),
      I('Peki acil durum ne?', { g: 'explain' }),
      Y('Bugün cuma. Cuma günü ne isteyeceğini bilmiyorum. Bilinmezlik, acil durumdur.', { e: 'serious', g: 'raise' }),
      I('Yılmaz. Beni sabahın yedisinde, pijamayla bunun için mi kaldırdın?', { e: 'angry', g: 'explain' }),
      Y('Pijamayla gelmeni ben istemedim. O senin tercihin.', { e: 'neutral' }),
      I('Sen "acil" dedin!', { e: 'angry', g: 'point' }),
      Y('Acil dedim. "Pijamayla gel" demedim. Acil durumda insan giyinir. Yangında bile giyinik çıkmak lazım.', { g: 'explain' }),
      I('Ne yapmamı istiyorsun?', { e: 'tired', g: 'hips' }),
      Y('Planım şu. Sen benim paltomu giyeceksin, şapkamı takacaksın ve kapıdan çıkacaksın.', { g: 'explain', e: 'smug' }),
      I('Sonra?'),
      Y('Necmi Bey seni ben sanacak. Senden bir şey isteyecek. Sen onu oyalarken ben arkandan sessizce çıkıp işe gideceğim.', { g: 'explain' }),
      I('Ben ne vereceğim adama?'),
      Y('Vermeyeceksin. "Yok" diyeceksin.', { g: 'stop' }),
      I('Sen neden "yok" demiyorsun?', { g: 'shrug' }),
      Y('Ben diyemiyorum İlkkan. Ben komşuluk ilişkisine inanan bir insanım.', { e: 'sad', g: 'heart' }),
      I('Ben inanmıyor muyum?', { e: 'angry' }),
      Y('Sen benim komşum değilsin ki. Senin komşuluk sorumluluğun yok. Rahatsın.', { e: 'happy', g: 'explain' }),
      act('İlkkan düşünür.', [{ g: 'ilk', v: 'think' }], { cam: 'cu:ilk' }),
      I('Bu mantık... bir yerde doğru gibi.', { e: 'neutral', g: 'think' }),
      Y('Doğru gibi değil, doğru. Al şu paltoyu.', { e: 'serious', g: 'point' }),
      act('Yılmaz askıdan paltoyu ve şapkayı alır. İlkkan pijamasının üstüne giyer, şapkayı takar. Palto ona iki beden büyüktür.', [
        { mv: 'yil', to: [-3.6, 1.3], sp: 1.1 }, { face: 'yil', at: [-4.2, 1.7] },
        { vis: 'B.rack', v: 0 }, { hold: 'yil', v: 'coat' },
        { mv: 'yil', to: [-2.9, 1.0], sp: 1 }, { face: 'yil', at: 'ilk' },
        { hold: 'yil', v: null }, { fit: 'ilk', v: 'coat' }, { sfx: 'cloth', par: true },
        { g: 'ilk', v: 'present' }, { wait: 0.3 },
      ], { cam: 'wide' }),
      Y('Anahtarı da buraya bırak. Anahtarın yeri burası.', { g: 'point', do: [{ face: 'yil', at: [-4.15, -0.6] }] }),
      act('İlkkan anahtarı kapının yanındaki konsolun üstündeki kâseye bırakır.', [
        { mv: 'ilk', to: [-3.55, -0.55], sp: 1 }, { face: 'ilk', at: -90 },
        { hold: 'ilk', v: null }, { vis: 'B.bowlKey', v: 1 }, { sfx: 'keys', par: true },
        { face: 'ilk', at: 'yil' }, { face: 'yil', at: 'ilk', par: true },
      ], { cam: 'wide' }),
      I('Ben Yılmaz\'a benzemiyorum ama.', { e: 'sad', g: 'shrug' }),
      Y('Dürbünden herkes birbirine benzer. Dürbün bir balık gözüdür. Balık için bütün insanlar aynıdır.', { e: 'serious', g: 'explain' }),
      I('Necmi Bey balık mı?', { e: 'surprised' }),
      Y('Sabahları öyle.', { e: 'serious', cam: 'cu:yil', pause: 0.6 }),
    ],
  },
  // ======================================================================
  {
    id: 'koridor',
    label: 'SAHNE 3',
    heading: 'İÇ. APARTMAN KORİDORU – DEVAM',
    set: 'C',
    time: 'morning',
    ambience: 'hall',
    cast: {
      ilk: { pos: [-2.0, -3.2], yaw: 0, outfit: 'coat' },
      nec: { pos: [2.2, -3.4], yaw: 0, hidden: true },
      yil: { pos: [-2.0, -3.6], yaw: 0, hidden: true },
    },
    beats: [
      act('Yedi numaranın kapısı açılır. Paltolu, şapkalı İlkkan dikkatle koridora çıkar. Kapıyı arkasından aralık bırakır.', [
        { door: 'C7', v: 0.8, dur: 0.6 }, { sfx: 'doorOpen', par: true },
        { mv: 'ilk', to: [-1.8, -1.2], sp: 0.8 }, { door: 'C7', v: 0.2, dur: 0.8 },
        { face: 'ilk', at: 0 }, { wait: 0.5 },
      ], { cam: 'wide' }),
      act('Daha üç adım atmadan sekiz numaranın kapısı açılır. Hırkalı, gözlüklü Necmi Bey belirir.', [
        { door: 'C8', v: 0.9, dur: 0.35 }, { sfx: 'doorOpen', par: true },
        { show: 'nec' }, { mv: 'nec', to: [1.6, -1.2], sp: 1.6 }, { face: 'nec', at: 'ilk' },
        { face: 'ilk', at: 'nec', par: true }, { g: 'ilk', v: 'jump', par: true },
      ], { cam: 'wide' }),
      N('Yılmaz Bey! Günaydın! Bir şey isteyeceğim.', { e: 'happy', g: 'wave' }),
      I('Yok.', { e: 'serious', p: 'sesini kalınlaştırarak', g: 'stop' }),
      N('Daha ne istediğimi söylemedim.', { e: 'surprised' }),
      I('Ne istersen yok.', { e: 'serious', g: 'cross' }),
      act('Necmi Bey gözlüğünü düzeltir, İlkkan\'ı tepeden tırnağa süzer.', [{ g: 'nec', v: 'glasses' }, { mv: 'nec', to: [0.6, -1.0], sp: 0.6 }, { face: 'nec', at: 'ilk' }], { cam: 'cu:nec' }),
      N('Siz Yılmaz Bey değilsiniz.', { e: 'serious' }),
      I('Benim.', { e: 'scared' }),
      N('Yılmaz Bey "yok" demez. Yılmaz Bey bir beyefendidir. Modemini verdi.', { g: 'explain' }),
      I('...Peki. Ben Yılmaz değilim.', { e: 'sad', pause: 0.2 }),
      N('Belli. Palto Yılmaz Bey\'in ama.', { g: 'point' }),
      I('Palto onun, içi benim.', { g: 'present' }),
      N('Olsun. Palto Yılmaz Bey\'inse, paltonun cebindeki de Yılmaz Bey\'indir. Bir yumurta isteyecektim.', { e: 'happy', g: 'explain' }),
      I('Paltonun cebinde yumurta yok.', { e: 'tired', g: 'shrug' }),
      N('Mutfakta vardır.', { e: 'smug' }),
      I('Yumurtayı ne yapacaksınız?'),
      N('Kahvaltı. Ama benim tavam yok. Tavayı da isteyecektim.', { e: 'sad' }),
      I('Tava da mı?', { e: 'surprised' }),
      N('Ocağım da bozuk. Aslında yumurtayı Yılmaz Bey\'in ocağında yapsam, tava da yumurta da yerinden hiç oynamaz. Kimse kimseye bir şey vermemiş olur.', { g: 'explain' }),
      I('Bu... aslında çok mantıklı.', { e: 'neutral', g: 'think' }),
      N('Komşuluk mantıktır evladım.', { e: 'smug', g: 'raise' }),
      act('Bu sırada arkadan, yedi numaranın aralık kapısından Yılmaz parmak uçlarında çıkar. Merdivenlere doğru süzülür.', [
        { show: 'yil' }, { door: 'C7', v: 0.75, dur: 0.6 }, { sfx: 'creak', par: true },
        { mv: 'yil', to: [-2.0, -1.9], sp: 0.5 }, { pose: 'yil', v: 'tiptoe' },
        { mv: 'yil', to: [-0.4, -2.0], sp: 0.45 },
      ], { cam: 'wide' }),
      act('Necmi Bey başını çevirir.', [{ look: 'nec', at: 'yil' }, { wait: 0.4 }], { cam: 'cu:nec' }),
      N('Günaydın Yılmaz Bey!', { e: 'happy', g: 'wave', to: 'yil' }),
      act('Yılmaz olduğu yerde donar.', [{ pose: 'yil', v: null }, { g: 'yil', v: 'freeze' }, { face: 'yil', at: 'nec' }], { cam: 'cu:yil' }),
      Y('...Günaydın Necmi Bey.', { e: 'scared', to: 'nec' }),
      N('Bu bey sizin paltonuzu giymiş.', { g: 'point', to: 'yil' }),
      Y('Farkındayım. Ödünç verdim.', { e: 'neutral', to: 'nec' }),
      N('Ne güzel. Demek siz de ödünç veriyorsunuz.', { e: 'happy', to: 'yil' }),
      act('Yılmaz yan yan İlkkan\'a yaklaşır.', [{ mv: 'yil', to: [-1.1, -1.3], sp: 0.9 }, { face: 'yil', at: 'ilk' }, { face: 'ilk', at: 'yil', par: true }], { cam: 'two' }),
      Y('Plan bozuldu.', { p: 'fısıltıyla', e: 'serious', to: 'ilk' }),
      I('Plan başından beri bozuktu!', { e: 'angry', to: 'yil', p: 'fısıltıyla' }),
      act('Merdiven boşluğundan bir rüzgâr eser. Yedi numaranın kapısı "güm" diye çarpar. Üçü de kapıya döner.', [
        { sfx: 'wind' }, { wait: 0.6 }, { door: 'C7', v: 0, dur: 0.2 }, { sfx: 'slam', par: true },
        { g: 'ilk', v: 'jump', par: true }, { g: 'yil', v: 'jump', par: true }, { g: 'nec', v: 'jump', par: true },
        { look: 'ilk', at: [-2.0, 1.2, -2.5] }, { look: 'yil', at: [-2.0, 1.2, -2.5], par: true }, { look: 'nec', at: [-2.0, 1.2, -2.5], par: true },
        { wait: 1.2 },
      ], { cam: 'wide' }),
      I('Kapı...', { e: 'scared', look: [-2.0, 1.2, -2.5] }),
      Y('Kapandı.', { e: 'serious', look: [-2.0, 1.2, -2.5], cam: 'crash:yil' }),
      I('Anahtar?', { e: 'scared', to: 'yil' }),
      Y('Kâsede. Anahtarın yeri orası.', { to: 'ilk' }),
      I('Senin anahtarın?', { e: 'angry' }),
      Y('O da içerde. Ben evden çıkmıyordum ki. Sen çıkıyordun.', { g: 'explain' }),
      I('Yedeğin yedeği?', { e: 'scared' }),
      Y('Çekmecede. Yedeğin yedeği evde durur. Kural bu.', { e: 'serious', g: 'raise' }),
      N('Yumurta da içeride kaldı.', { e: 'sad', to: 'yil' }),
      BOTH('Necmi Bey!', { e: 'angry', to: 'nec', g: 'point' }),
      act('Kısa bir sessizlik. Yılmaz yavaşça İlkkan\'a döner.', [{ face: 'yil', at: 'ilk' }, { look: 'yil', at: 'ilk' }, { wait: 0.6 }], { cam: 'cu:yil' }),
      Y('İlkkan.', { to: 'ilk', e: 'serious' }),
      I('Ne?', { to: 'yil' }),
      Y('Acil durum.', { e: 'serious', cam: 'cu:yil' }),
      I('Biliyorum!', { e: 'angry', g: 'flail', pause: 0.5 }),
    ],
  },
  // ======================================================================
  {
    id: 'kapici',
    label: 'SAHNE 4',
    heading: 'İÇ. APARTMAN GİRİŞİ – KAPICI MASASI – SABAH',
    set: 'D',
    time: 'morning',
    ambience: 'hall',
    cast: {
      rem: { pos: [2.6, -2.15], yaw: 0, sit: true, hold: 'paper', look: [2.6, 0.9, -1.0] },
      yil: { pos: [-3.85, -2.75], y: 1.5, yaw: 180 },
      ilk: { pos: [-3.85, -3.4], y: 1.85, yaw: 180, outfit: 'coat' },
      nec: { pos: [-3.85, -4.0], y: 2.1, yaw: 180 },
    },
    beats: [
      act('Kapıcı Remzi masasında gazetesini okuyor, çayı demleniyor. Üçü merdivenlerden peş peşe iner.', [
        { wait: 0.6 },
        { mv: 'yil', to: [-3.85, -0.8], y: 0, sp: 1.2 }, { mv: 'ilk', to: [-3.85, -0.8], y: 0, sp: 1.2, par: true, delay: 0.5 },
        { mv: 'nec', to: [-3.85, -0.8], y: 0, sp: 1.0, par: true, delay: 1.1 },
      ], { cam: 'wide', parAll: true }),
      act('Remzi gazeteyi indirir.', [
        { mv: 'yil', to: [0.9, -0.9], sp: 1.2 }, { mv: 'ilk', to: [-0.4, -0.2], sp: 1.2, par: true, delay: 0.3 },
        { mv: 'nec', to: [-1.4, -0.9], sp: 1.0, par: true, delay: 0.8 },
        { face: 'yil', at: 'rem' }, { face: 'ilk', at: 'rem', par: true }, { face: 'nec', at: 'rem', par: true },
        { hold: 'rem', v: 'tea' }, { look: 'rem', at: 'yil', par: true },
      ], { cam: 'wide' }),
      R('Hayırdır beyler? Sabah sabah heyet halinde.', { e: 'smug', to: 'yil' }),
      Y('Remzi Efendi, kapıda kaldık.', { e: 'sad', to: 'rem' }),
      R('Geçmiş olsun.', { do: [{ g: 'rem', v: 'sip' }] }),
      I('Sizde dairelerin yedek anahtarı var, değil mi?', { to: 'rem', g: 'explain' }),
      R('Var. Bütün dairelerin anahtarı bende. Bir tek Yılmaz Bey\'inki hariç.', { to: 'ilk', g: 'raise' }),
      act('İlkkan yavaşça Yılmaz\'a döner.', [{ face: 'ilk', at: 'yil' }, { look: 'ilk', at: 'yil' }, { wait: 0.5 }], { cam: 'cu:ilk' }),
      I('Neden?', { to: 'yil', e: 'angry' }),
      Y('Çünkü kapıcıya anahtar verilmez İlkkan.', { to: 'ilk', e: 'serious', do: [{ face: 'yil', at: 'ilk' }] }),
      R('Aynen öyle dedi. "Kapıcı kapıyı bekler, kapıyı açmaz" dedi.', { to: 'ilk', e: 'neutral' }),
      Y('Kapıcı kelimesinin içinde "kapı" var, "açıcı" yok.', { g: 'raise', e: 'smug' }),
      I('Çilingir kelimesinin içinde ne var peki?', { e: 'angry' }),
      Y('Hiçbir şey yok. O yüzden çilingire güvenmiyorum.', { e: 'serious', g: 'cross' }),
      R('Çilingir çağıralım o zaman. Hüsnü Usta var, köşede.', { to: 'yil' }),
      Y('Olmaz. Çilingir kapıyı açarsa, o ev artık çilingirin de evi olur.', { to: 'rem', g: 'stop' }),
      I('Ne alakası var?', { g: 'shrug' }),
      Y('Bir kapıyı kim açabiliyorsa, o ev biraz onundur İlkkan.', { e: 'serious', g: 'explain', to: 'ilk' }),
      I('O zaman senin ev biraz benim de mi?', { e: 'surprised' }),
      Y('Sen yedek anahtarlısın. Sen... kiracı gibisin.', { e: 'neutral' }),
      I('Kira mı vereceğim?', { e: 'angry', g: 'flail' }),
      Y('Acil durumlarda.', { e: 'serious', cam: 'cu:yil' }),
      N('Ben Hüsnü Usta\'yı aradım bile.', { e: 'happy', g: 'phoneShow', to: 'yil' }),
      Y('Necmi Bey!', { e: 'angry', to: 'nec', do: [{ face: 'yil', at: 'nec' }] }),
      N('Yumurta içeride Yılmaz Bey. Yumurta beklemez.', { e: 'serious', g: 'raise' }),
      R('Çay koyayım mı?', { e: 'happy', to: 'ilk', g: 'present' }),
      I('Koy Remzi Abi, koy. Uzun gün olacak.', { e: 'tired', to: 'rem', pause: 0.6 }),
    ],
  },
  // ======================================================================
  {
    id: 'cilingir',
    label: 'SAHNE 5',
    heading: 'DIŞ. HUZUR APARTMANI ÖNÜ – SOKAK – GÜNDÜZ',
    set: 'E',
    time: 'day',
    ambience: 'street',
    cast: {
      yil: { pos: [-0.9, 0.0], yaw: -60, hold: 'tea' },
      ilk: { pos: [0.4, -0.2], yaw: -80, outfit: 'coat', hold: 'tea' },
      nec: { pos: [1.5, -0.5], yaw: -90 },
      hus: { pos: [-6.6, 2.7], yaw: 90, hidden: true, hold: 'toolbox' },
    },
    beats: [
      act('Apartmanın önünde, ellerinde çay bardaklarıyla bekliyorlar. Üzerinde "HÜSNÜ ÇİLİNGİR 7/24" yazan küçük bir minibüs gelip durur.', [
        { van: 'go' }, { sfx: 'van', par: true }, { wait: 3.4 }, { sfx: 'vanDoor' },
        { show: 'hus' }, { mv: 'hus', to: [-2.2, 0.5], sp: 1.2 },
        { face: 'hus', at: 'yil' }, { face: 'yil', at: 'hus', par: true }, { face: 'ilk', at: 'hus', par: true }, { face: 'nec', at: 'hus', par: true },
      ], { cam: 'wide' }),
      H('Selamünaleyküm. Kapısı kapanan kim?', { g: 'wave', to: 'yil' }),
      Y('Kapandı demeyelim. Kendi kendine kapandı.', { to: 'hus', g: 'raise' }),
      H('Fark eder mi?', { e: 'surprised' }),
      Y('Eder. Ben kapatmadım. Rüzgâr kapattı. Rüzgârın çilingire ihtiyacı yok.', { e: 'serious', g: 'explain' }),
      H('Abi, kapı kimin?', { e: 'tired' }),
      Y('Benim.'),
      H('O zaman açayım mı?', { g: 'shrug' }),
      Y('Önce fiyat.', { e: 'smug', g: 'raise' }),
      H('Kapı başı beş yüz. Muhabbet ayrı.', { e: 'smug' }),
      I('Muhabbet ne kadar?', { to: 'hus', e: 'surprised' }),
      H('Bu muhabbet şimdiden üç yüz oldu.', { to: 'ilk', e: 'serious', g: 'point' }),
      Y('Açmak mı beş yüz, aralamak mı?', { to: 'hus' }),
      H('Ne farkı var?', { g: 'shrug' }),
      Y('Açmak, kapıyı tamamen açmaktır. Aralamak, kapıyı ben açayım diye hazır etmektir. Son hamleyi ben yapacağım. Ev benim kalsın.', { g: 'explain', e: 'serious' }),
      H('Abi ben kapıyı açarım, sen içeri girersin. Ev senin kalır.', { e: 'tired', g: 'explain' }),
      Y('Söz mü?', { e: 'serious', g: 'point' }),
      H('Usta sözü.', { e: 'smug', g: 'heart', pause: 0.5 }),
    ],
  },
  // ======================================================================
  {
    id: 'kilit',
    label: 'SAHNE 6',
    heading: 'İÇ. APARTMAN KORİDORU – YEDİ NUMARANIN ÖNÜ',
    set: 'C',
    time: 'morning',
    ambience: 'hall',
    cast: {
      hus: { pos: [-2.0, -1.75], yaw: 180, hold: 'card' },
      yil: { pos: [-0.9, -0.8], yaw: -140 },
      ilk: { pos: [-0.1, -0.5], yaw: -130, outfit: 'coat' },
      nec: { pos: [0.9, -0.9], yaw: -110 },
    },
    beats: [
      act('Hüsnü Usta kapının önüne çömelir gibi eğilir, bir plastik kartı kapı aralığına sokar. Kart bir kez kayar.', [
        { g: 'hus', v: 'work' }, { sfx: 'scratch', par: true }, { wait: 0.4 }, { sfx: 'click' },
        { door: 'C7', v: 0.85, dur: 0.6 }, { sfx: 'creak', par: true },
        { face: 'hus', at: 'yil' }, { hold: 'hus', v: null },
      ], { cam: 'cu:hus' }),
      H('Buyurun.', { e: 'smug', g: 'present', to: 'yil' }),
      Y('Üç saniye!', { e: 'scared', cam: 'crash:yil', g: 'flail', to: 'hus' }),
      H('İki buçuk. Kapı eski.', { e: 'neutral' }),
      Y('Demek ki bu kapı herkese açıkmış! Bunca yıl ben bir hiçin içinde yaşamışım!', { e: 'scared', g: 'flail' }),
      I('Yılmaz, abartma.', { to: 'yil', e: 'tired', g: 'stop' }),
      Y('Abartmıyorum. Kilidi değiştireceğiz. Hemen.', { to: 'hus', e: 'serious', g: 'point' }),
      H('Değiştiririm. Yeni kilit bin beş yüz. Üç anahtarlı.', { e: 'smug', g: 'count3' }),
      Y('Üç mü? Bir asıl, bir yedek, bir yedeğin yedeği. Tam istediğim gibi.', { e: 'happy', g: 'count3' }),
      act('Necmi Bey kimseye sormadan açık kapıdan içeri süzülür.', [
        { mv: 'nec', to: [-1.4, -1.6], sp: 1.0 }, { mv: 'nec', to: [-2.0, -3.4], sp: 1.0 }, { hide: 'nec' },
      ], { cam: 'wide' }),
      N('Ben mutfağa geçiyorum Yılmaz Bey!', { os: true, to: 'yil', e: 'happy' }),
      Y('Buyurun Necmi Bey.', { e: 'happy', to: 'ilk', pause: 0.5 }),
      act('Yılmaz durur. Yavaşça İlkkan\'a döner.', [{ face: 'yil', at: 'ilk' }, { face: 'ilk', at: 'yil', par: true }, { wait: 0.4 }], { cam: 'two' }),
      Y('Neden "buyurun" dedim?', { e: 'surprised', to: 'ilk' }),
      I('Komşuluk ilişkisine inanıyorsun.', { e: 'smug', to: 'yil', pause: 0.6 }),
    ],
  },
  // ======================================================================
  {
    id: 'final',
    label: 'SAHNE 7',
    heading: 'İÇ. YILMAZ\'IN EVİ – SALON – ÖĞLEN',
    set: 'B',
    time: 'day',
    ambience: 'kitchen',
    list: 4,
    cast: {
      nec: { pos: [3.35, -1.6], yaw: 90, hold: 'pan' },
      yil: { pos: [-2.2, 0.3], yaw: 70, hold: 'key' },
      ilk: { pos: [-0.9, 0.5], yaw: -100, outfit: 'coat' },
    },
    flags: { 'B.bowlKey': 1, 'B.rack': 0 },
    beats: [
      act('Kapıya yeni, parlak bir kilit takılmış. Mutfakta Necmi Bey tavada yumurta pişiriyor. Yılmaz yeni anahtarı törenle İlkkan\'a uzatır.', [
        { wait: 1.2 }, { g: 'yil', v: 'present' },
      ], { cam: 'wide' }),
      Y('İlkkan. Bu yeni yedek.', { e: 'serious', g: 'present' }),
      act('İlkkan anahtarı alır.', [{ hold: 'yil', v: null }, { hold: 'ilk', v: 'key' }, { g: 'ilk', v: 'inspect' }]),
      I('Teşekkür ederim. Kalbime koyacağım.', { e: 'happy', g: 'heart' }),
      Y('Anahtarlığa tak.', { e: 'neutral' }),
      I('Acil durum listesi aynı mı?'),
      act('Yılmaz başıyla duvardaki çerçeveyi işaret eder. Listenin altına el yazısıyla dördüncü bir madde eklenmiş.', [
        { look: 'yil', at: [-2.2, 1.7, -3] }, { look: 'ilk', at: [-2.2, 1.7, -3], par: true }, { wait: 1.6 },
      ], { cam: { pos: [-2.2, 1.65, -1.2], look: [-2.2, 1.65, -3] } }),
      Y('Bir madde ekledim. Dört: Necmi Bey.', { e: 'serious', g: 'count1' }),
      I('Mantıklı.', { g: 'nod' }),
      Y('Yedeğin yedeğini de artık çekmeceye koymuyorum. Ders aldım.', { g: 'raise' }),
      I('Nereye koyacaksın?'),
      Y('Güvendiğim, kapıya yakın, her sabah evde olan birine verdim.', { e: 'smug', g: 'explain' }),
      I('Kime?', { e: 'surprised' }),
      act('Yılmaz mutfağa doğru bakar.', [{ look: 'yil', at: 'nec' }, { wait: 0.8 }], { cam: 'cu:yil' }),
      N('Teşekkür ederim Yılmaz Bey! Emanetiniz bende!', { e: 'happy', g: 'wave', to: 'yil', do: [{ face: 'nec', at: 'yil' }] }),
      I('Yılmaz... sen yedeğin yedeğini Necmi Bey\'e mi verdin?', { e: 'scared', to: 'yil', do: [{ face: 'ilk', at: 'yil' }] }),
      Y('Kapıyı bekleyen biri lazımdı. Kapıcı açmıyor.', { to: 'ilk', e: 'serious' }),
      I('Ama adam her sabah senden bir şey istiyor!', { e: 'angry', g: 'flail' }),
      Y('Artık istemeyecek. Çünkü artık bende onun bir şeyi yok. Onda benim bir şeyim var. Dengelendik.', { e: 'happy', g: 'explain' }),
      act('Necmi Bey elinde tavayla mutfaktan çıkar.', [
        { mv: 'nec', to: [1.0, -0.3], sp: 0.9 }, { face: 'nec', at: 'yil' },
        { look: 'yil', at: 'nec', par: true }, { look: 'ilk', at: 'nec', par: true },
      ], { cam: 'wide' }),
      N('Yılmaz Bey, bir şey isteyeceğim.', { e: 'happy', to: 'yil', g: 'raise' }),
      act('Yılmaz ve İlkkan birbirine bakar.', [{ look: 'yil', at: 'ilk' }, { look: 'ilk', at: 'yil', par: true }, { wait: 0.9 }], { cam: 'two' }),
      BOTH('Acil durum!', { e: 'scared', g: 'flail' }),
      act('İkisi kapıya fırlar ve çıkar. Kapı arkalarından çarpar. Necmi Bey elinde tavayla tek başına kalır.', [
        { hold: 'ilk', v: null },
        { mv: 'yil', to: [-3.7, 0.6], sp: 3.4 }, { mv: 'ilk', to: [-3.2, 0.9], sp: 3.4, par: true },
        { door: 'B', v: 1, dur: 0.2 }, { sfx: 'doorOpen', par: true },
        { mv: 'yil', to: [-5.8, 0.6], sp: 3.4 }, { mv: 'ilk', to: [-5.8, 0.6], sp: 3.4, par: true, delay: 0.25 },
        { door: 'B', v: 0, dur: 0.18 }, { sfx: 'slam', par: true },
        { look: 'nec', at: [-4.5, 1.3, 0.6] }, { wait: 1.2 },
      ], { cam: 'wide' }),
      N('Bir tuz isteyecektim.', { e: 'sad', to: 'ilk', look: [-4.5, 1.3, 0.6], cam: 'cu:nec', pause: 0.6 }),
    ],
  },
  // ======================================================================
  {
    id: 'tag',
    label: 'SON',
    heading: 'İÇ. APARTMAN KORİDORU – AZ SONRA',
    set: 'C',
    time: 'day',
    ambience: 'hall',
    cast: {
      yil: { pos: [-2.55, -1.75], yaw: 0, sit: 'floor' },
      ilk: { pos: [-1.45, -1.75], yaw: 0, sit: 'floor', outfit: 'coat' },
    },
    beats: [
      act('Yılmaz ve İlkkan, yedi numaranın önündeki paspasa yan yana oturmuşlar.', [{ wait: 2.0 }], { cam: 'wide' }),
      I('Anahtar?', { to: 'yil', e: 'tired' }),
      Y('İçerde. Kâsede.', { to: 'ilk' }),
      I('Benimki?'),
      Y('Seninki de kâsede. Anahtarın yeri orası.', { e: 'serious' }),
      I('Yedeğin yedeği?', { e: 'sad' }),
      Y('Necmi Bey\'de.', { e: 'neutral' }),
      act('İlkkan kalkıp kapıyı çalar.', [
        { stand: 'ilk' }, { face: 'ilk', at: 180 }, { sfx: 'knock' }, { wait: 0.8 },
      ], { cam: 'wide' }),
      N('Açamam Yılmaz Bey! Misafir varken kapı açılmaz, ayıp olur!', { os: true, e: 'serious', to: 'yil' }),
      act('İlkkan yeniden yere çöker.', [{ face: 'ilk', at: 0 }, { sit: 'ilk', at: [-1.45, -1.75], yaw: 0, h: 'floor' }]),
      I('Misafir kim?', { to: 'yil' }),
      Y('Biz... galiba.', { e: 'sad', to: 'ilk' }),
      I('Kendi evinde misafir mi oldun?', { e: 'surprised' }),
      Y('Hayat bu İlkkan. Bazen kendi evinin misafiri olursun.', { e: 'serious', cam: 'cu:yil' }),
      I('Bu çok derin bir söz gibi.', { e: 'neutral' }),
      Y('Gibi.', { e: 'smug', cam: 'cu:yil', pause: 1.4 }),
    ],
  },
  // ======================================================================
  {
    id: 'kapanis',
    label: 'KAPANIŞ JENERİĞİ',
    heading: 'KAPANIŞ JENERİĞİ',
    credits: true,
    beats: [{ type: 'credits', dur: 14 }],
  },
];
