// GİBİ — "Şifre" (hayran bölümü 2)
// "Yedek Anahtar"ın devamı: Yılmaz'ın modemi hâlâ Necmi Bey'dedir ve
// Necmi Bey şifreyi değiştirmiştir. Derbiye 22 dakika vardır.
//
// Koordinatlar her setin yerel düzlemindedir (bkz. src/layout.js).

export const meta = {
  series: 'GİBİ',
  title: 'Şifre',
  tag: 'Hayran Bölümü 2',
  logline:
    'Derbiye yirmi iki dakika kala Yılmaz\'ın evinde internet yoktur: modem hâlâ ' +
    'Necmi Bey\'dedir ve Necmi Bey şifreyi değiştirmiştir. Kendi internetinin ' +
    'şifresini aramak, Yılmaz\'ı ve İlkkan\'ı apartmanın, kapıcının ve bakkalın ' +
    'bildiği ama kimsenin söylemediği şeylerin peşine düşürür.',
  credits: [
    ['Yılmaz', 'kendisi gibi'], ['İlkkan', 'kendisi gibi'], ['Necmi Bey', 'sekiz numara'],
    ['Kapıcı Remzi', 'Huzur Apartmanı'], ['Bakkal Şükrü', 'veresiye defteri'],
  ],
  outro: ['Şifrenizi kimseye söylemeyin.', 'Kendinize bile.'],
};

export const cast = {
  yil: { name: 'YILMAZ', voice: { pitch: -1.5, speed: 1.06, noise: 0.62 } },
  ilk: { name: 'İLKKAN', voice: { pitch: 1.2, speed: 0.96, noise: 0.7 } },
  nec: { name: 'NECMİ BEY', voice: { pitch: 3.2, speed: 1.12, noise: 0.75 } },
  rem: { name: 'KAPICI REMZİ', voice: { pitch: -3.6, speed: 1.0, noise: 0.6 } },
  suk: { name: 'BAKKAL ŞÜKRÜ', voice: { pitch: 0.3, speed: 1.12, noise: 0.85 } },
};

const say = (who) => (text, o = {}) => ({ type: 'say', who, text, ...o });
const Y = say('yil');
const I = say('ilk');
const N = say('nec');
const R = say('rem');
const S = say('suk');
const BOTH = (text, o = {}) => ({ type: 'say', who: ['yil', 'ilk'], text, p: 'birlikte', ...o });
const act = (text, ops = [], o = {}) => ({ type: 'act', text, ops, ...o });
const card = (text, dur = 2.4, o = {}) => ({ type: 'card', text, dur, ...o });
// telefon / defter ekranı (tam ekran ara görüntü)
const insert = (text, o) => ({ type: 'insert', text, ...o });

const TV = [4.2, 1.15, 1.3]; // Yılmaz'ın televizyonu (yerel)

export const scenes = [
  // ======================================================================
  {
    id: 'acilis',
    label: 'SOĞUK AÇILIŞ',
    heading: 'İÇ. YILMAZ\'IN EVİ – SALON – AKŞAM, 20.38',
    set: 'B',
    time: 'night',
    ambience: 'room',
    list: 4,
    flags: { 'B.bowlKey': 1, 'B.rack': 1, 'B.tv': 'nosignal' },
    cast: {
      yil: { pos: [-0.5, -2.05], yaw: 0, sit: true, hold: 'remote', look: TV },
      ilk: { pos: [1.7, 0.7], yaw: 120, hold: 'phone' },
    },
    beats: [
      act('Yılmaz\'ın evi. Televizyonda mavi bir ekran: "İnternet bağlantısı yok." Yılmaz kanepede, elinde kumanda, ekrana sakin sakin bakıyor. İlkkan telefonunu havaya kaldırmış, odada çekim arıyor.', [
        { wait: 0.8 }, { mv: 'ilk', to: [3.0, 0.2], sp: 0.8 }, { g: 'ilk', v: 'phoneShow' },
        { mv: 'ilk', to: [1.2, 1.1], sp: 0.8 }, { g: 'ilk', v: 'phoneShow' }, { face: 'ilk', at: 'yil' },
      ], { cam: 'wide' }),
      I('Yılmaz, maç dokuzda. Saat sekiz buçuğu geçti. İnternet nerede?', { e: 'angry', g: 'explain' }),
      Y('Necmi Bey\'de.', { e: 'neutral', look: 'ilk' }),
      I('Necmi Bey\'de mi?', { e: 'surprised' }),
      Y('Perşembe günü modemimi istedi. Verdim. Anlattım ya sana.', { g: 'shrug' }),
      I('Anlattın ama ben geri aldın sanıyordum!', { e: 'angry', g: 'flail' }),
      Y('Verilen şey geri alınmaz İlkkan.', { e: 'serious', g: 'raise' }),
      I('Neden?'),
      Y('Geri alınırsa verilmemiş olur. Verilmemişse ben ona perşembe günü ne verdim?', { g: 'explain' }),
      I('Modem verdin!', { e: 'angry', g: 'point' }),
      Y('İşte. Verdim. Demek ki geri alamam.', { e: 'smug' }),
      act('İlkkan bir an gözlerini kapatır.', [{ g: 'ilk', v: 'facepalm' }], { cam: 'cu:ilk' }),
      I('Peki. Modem Necmi Bey\'deyse, interneti kim kullanıyor?', { e: 'tired' }),
      Y('Necmi Bey. Faturayı ben ödüyorum.', { e: 'neutral' }),
      I('Sen Necmi Bey\'in internet faturasını mı ödüyorsun?', { e: 'surprised', g: 'shrug' }),
      Y('Hayır. Ben kendi internet faturamı ödüyorum. Necmi Bey kullanıyor. Arada fark var.', { e: 'serious', g: 'explain' }),
      I('Ne fark var?'),
      Y('İnternet benim. Ben kullanmıyorum diye benim olmaktan çıkmaz.', { e: 'serious', g: 'heart' }),
      act('İlkkan telefonuna bakar. Ekranda kablosuz ağların listesi.', [{ g: 'ilk', v: 'inspect' }], { cam: 'cu:ilk' }),
      insert('Telefon ekranı: kablosuz ağlar.', {
        kind: 'wifi', dur: 3.6,
        rows: [['Yilmaz_Ev', 4], ['NecmiBey_Misafir', 3], ['HuzurApt_Kapici', 2], ['Sukru_Bakkal_7-24', 1]],
      }),
      I('Yılmaz! Senin ağın burada! "Yılmaz Ev". Hem de tam çekiyor!', { e: 'happy', g: 'phoneShow' }),
      Y('Duvarın öbür tarafında. Necmi Bey\'in salonunda. Benim evime bakıyor.', { e: 'sad', look: [-4.5, 1.5, -1.0] }),
      I('Şifresi ne?'),
      Y('Bilmiyorum.', { e: 'neutral' }),
      I('Nasıl bilmiyorsun? Senin modemin!', { e: 'angry', g: 'explain' }),
      Y('Necmi Bey değiştirmiş. "Güvenlik için" dedi.', { g: 'raise' }),
      I('Kimden güvenlik?', { e: 'surprised' }),
      Y('Benden herhalde. Modemin eski sahibi benim. En büyük tehlike benim.', { e: 'serious' }),
      I('Git şifreyi iste o zaman!', { g: 'point' }),
      Y('Kendi internetimin şifresini komşumdan mı isteyeceğim İlkkan?', { e: 'sad', g: 'heart' }),
      I('Evet!', { e: 'angry' }),
      Y('...Bu çok ağır bir şey.', { e: 'sad', cam: 'cu:yil', pause: 0.3 }),
      I('Maç dokuzda Yılmaz. Derbi!', { e: 'angry', g: 'flail' }),
      Y('Tamam. Ama ben istemem. Sen istersin.', { e: 'serious', g: 'point' }),
      I('Neden ben?'),
      Y('Sen misafirsin. Misafirin isteği geri çevrilmez.', { e: 'smug', g: 'explain' }),
      I('Bu mantık... yine bir yerde doğru.', { e: 'tired', g: 'think', pause: 0.6 }),
    ],
  },
  // ======================================================================
  { id: 'jenerik', label: 'JENERİK', heading: 'JENERİK', title: true, beats: [{ type: 'title', dur: 6.5 }] },
  // ======================================================================
  {
    id: 'necmi',
    label: 'SAHNE 1',
    heading: 'İÇ. APARTMAN KORİDORU – SEKİZ NUMARANIN ÖNÜ – GECE',
    set: 'C',
    time: 'night',
    ambience: 'hall',
    cast: {
      ilk: { pos: [1.6, -1.2], yaw: 160, hold: 'phone' },
      yil: { pos: [0.3, -0.9], yaw: 140 },
      nec: { pos: [2.2, -3.4], yaw: 0, hidden: true },
    },
    beats: [
      card('MAÇA 18 DAKİKA', 2.2),
      act('İlkkan sekiz numaranın kapısını çalar. Yılmaz bir adım geride, saklanır gibi durur.', [
        { sfx: 'knock' }, { wait: 0.8 }, { mv: 'yil', to: [-0.2, -1.0], sp: 0.6 }, { face: 'yil', at: [2.2, -2.5] },
        { wait: 0.6 }, { door: 'C8', v: 0.9, dur: 0.6 }, { sfx: 'doorOpen', par: true },
        { show: 'nec' }, { mv: 'nec', to: [2.2, -1.95], sp: 1.0 }, { face: 'nec', at: 'ilk' },
      ], { cam: 'wide' }),
      N('İlkkan Bey! Hoş geldiniz. Yılmaz Bey de arkada. İkiniz birden. Hayırdır?', { e: 'happy', g: 'wave' }),
      I('Necmi Bey, kusura bakmayın. Bir şey isteyeceğim.', { e: 'neutral', to: 'nec' }),
      N('Benden mi? Benden bir şey isteniyor?', { e: 'surprised', g: 'heart', to: 'ilk' }),
      N('Bu apartmanda ilk defa oluyor.', { e: 'happy', to: 'ilk' }),
      Y('Tadını çıkarın Necmi Bey.', { e: 'serious', to: 'nec' }),
      I('İnternetin şifresini alabilir miyiz?', { to: 'nec', g: 'phoneShow' }),
      N('Hangi internetin?', { e: 'surprised' }),
      I('Yılmaz\'ın internetinin.'),
      N('Yılmaz Bey\'in interneti yok ki. Modemini bana verdi.', { e: 'neutral', g: 'explain' }),
      Y('Doğru söylüyor.', { to: 'ilk', e: 'neutral' }),
      I('Sen kimin tarafındasın?!', { to: 'yil', e: 'angry', g: 'flail', do: [{ face: 'ilk', at: 'yil' }] }),
      Y('Doğrunun.', { to: 'ilk', e: 'serious', cam: 'cu:yil' }),
      N('Şifreyi söyleyemem İlkkan Bey.', { to: 'ilk', e: 'serious', do: [{ face: 'ilk', at: 'nec' }] }),
      I('Neden?', { to: 'nec' }),
      N('Şifre söylenirse şifre olmaz. Şifre, söylenmeyen şeydir.', { e: 'serious', g: 'raise' }),
      Y('Bu çok doğru bir laf.', { e: 'happy', g: 'nod', to: 'nec' }),
      I('Yılmaz!', { e: 'angry', to: 'yil' }),
      N('Ama size bir ipucu veririm. Komşuluk bunu gerektirir.', { e: 'smug', to: 'ilk' }),
      I('Verin!', { e: 'happy', g: 'present' }),
      N('Şifre... bu apartmanda herkesin bildiği ama kimsenin söylemediği şeydir.', { e: 'smug', cam: 'cu:nec', pause: 0.4 }),
      act('Necmi Bey gülümser ve kapıyı yavaşça kapatır.', [
        { mv: 'nec', to: [2.2, -3.4], sp: 0.8 }, { hide: 'nec' }, { door: 'C8', v: 0, dur: 0.8 }, { sfx: 'doorClose', par: true },
        { face: 'ilk', at: 'yil' }, { face: 'yil', at: 'ilk', par: true },
      ], { cam: 'wide' }),
      I('Herkesin bildiği ama kimsenin söylemediği şey ne?', { e: 'surprised', to: 'yil' }),
      Y('Bu apartmanda çok şey var İlkkan.', { e: 'serious' }),
      I('Mesela?'),
      Y('Mesela üçüncü kattaki Nuran Hanım\'ın sesi. Herkes biliyor, kimse söylemiyor.', { e: 'smug', g: 'raise' }),
      I('Ne var sesinde?'),
      Y('Söylemem. Söylenmeyen şey o.', { e: 'serious', g: 'hush' }),
      I('Kapıcıya soralım. Kapıcı her şeyi bilir.', { g: 'point' }),
      Y('Bilir ama açmaz.', { e: 'neutral' }),
      I('Kapıyı açmaz! Ağzını açar!', { e: 'angry', g: 'flail', pause: 0.4 }),
    ],
  },
  // ======================================================================
  {
    id: 'kapici',
    label: 'SAHNE 2',
    heading: 'İÇ. APARTMAN GİRİŞİ – KAPICI MASASI – GECE',
    set: 'D',
    time: 'night',
    ambience: 'hall',
    cast: {
      rem: { pos: [2.6, -2.15], yaw: 0, sit: true, hold: 'tea', look: [2.6, 0.9, -1.0] },
      yil: { pos: [-3.85, -2.75], y: 1.5, yaw: 180 },
      ilk: { pos: [-3.85, -3.4], y: 1.85, yaw: 180, hold: 'phone' },
    },
    beats: [
      card('MAÇA 13 DAKİKA', 2.2),
      act('İkisi merdivenlerden koşarak iner. Remzi çayını yudumluyor.', [
        { mv: 'ilk', to: [-3.85, -0.8], y: 0, sp: 1.8 }, { mv: 'yil', to: [-3.85, -0.8], y: 0, sp: 1.6, par: true },
        { mv: 'ilk', to: [0.9, -0.7], sp: 1.8 }, { mv: 'yil', to: [-0.4, -0.2], sp: 1.6, par: true, delay: 0.3 },
        { face: 'ilk', at: 'rem' }, { face: 'yil', at: 'rem', par: true }, { look: 'rem', at: 'ilk', par: true },
      ], { cam: 'wide' }),
      R('Hayırdır beyler? Yine mi kapıda kaldınız?', { e: 'smug', to: 'yil' }),
      I('Remzi Abi, bu apartmanda herkesin bildiği ama kimsenin söylemediği şey ne?', { to: 'rem', g: 'explain' }),
      act('Remzi düşünür.', [{ g: 'rem', v: 'think' }, { wait: 0.4 }], { cam: 'cu:rem' }),
      R('Aidat.', { e: 'serious', to: 'ilk' }),
      Y('Doğru. Aidatı herkes biliyor, kimse söylemiyor. Ben de söylemedim. Üç aydır.', { e: 'neutral', g: 'count3', to: 'rem' }),
      R('Yılmaz Bey!', { e: 'angry', to: 'yil' }),
      insert('İlkkan şifre olarak "aidat" yazar.', { kind: 'pass', dur: 3.0, net: 'Yilmaz_Ev', input: 'aidat', ok: false }),
      I('Olmadı.', { e: 'sad', to: 'rem' }),
      R('Asansör o zaman. Panoda yazıyor: "Asansör yoktur." Herkes biliyor, yine de herkes soruyor.', { g: 'point', to: 'ilk', look: [1.6, 1.75, -3.0] }),
      insert('"asansoryok" yazar.', { kind: 'pass', dur: 3.0, net: 'Yilmaz_Ev', input: 'asansoryok', ok: false }),
      I('Olmadı!', { e: 'angry' }),
      R('Remzi\'nin çayı. Herkes biliyor ki soğuk. Kimse söylemiyor.', { e: 'sad', to: 'ilk', g: 'sip' }),
      Y('Sıcak Remzi Efendi.', { e: 'serious', to: 'rem' }),
      R('Sağ olun Yılmaz Bey.', { e: 'happy', to: 'yil' }),
      I('Yazayım mı "soğuk çay"?', { to: 'yil' }),
      Y('Yazma. Ayıp olur.', { to: 'ilk', e: 'serious', g: 'stop' }),
      I('Maça on üç dakika var Yılmaz!', { e: 'angry', g: 'flail' }),
      R('Bakkal Şükrü\'ye gidin. Necmi Bey her şeyi Şükrü\'nün veresiye defterine yazdırır. Ekmeğini, yumurtasını, hayatını.', { g: 'explain', to: 'ilk' }),
      Y('Veresiye defteri, bir mahallenin hafızasıdır.', { e: 'serious', g: 'raise', cam: 'cu:yil' }),
      I('Koş!', { e: 'angry', g: 'flail', pause: 0.2 }),
      act('İkisi kapıdan fırlar.', [
        { mv: 'ilk', to: [0, -2.4], sp: 3.2 }, { mv: 'yil', to: [0.1, -2.3], sp: 3.0, par: true, delay: 0.2 },
        { hide: 'ilk' }, { hide: 'yil', par: true }, { sfx: 'doorClose' }, { wait: 0.6 },
        { g: 'rem', v: 'sip' }, { wait: 1.0 },
      ], { cam: 'wide' }),
    ],
  },
  // ======================================================================
  {
    id: 'bakkal',
    label: 'SAHNE 3',
    heading: 'İÇ. ŞÜKRÜ\'NÜN BAKKALI – GECE',
    set: 'F',
    time: 'night',
    ambience: 'shop',
    cast: {
      suk: { pos: [3.1, -0.9], yaw: -90, hold: 'notebook' },
      yil: { pos: [-5.6, 0.6], yaw: 90 },
      ilk: { pos: [-6.2, 0.6], yaw: 90, hold: 'phone' },
    },
    beats: [
      card('MAÇA 9 DAKİKA', 2.2),
      act('Kapının zili çınlar. Yılmaz ve İlkkan bakkala girer. Tezgâhın arkasında Bakkal Şükrü, önünde kalın bir defter.', [
        { sfx: 'bell' },
        { mv: 'ilk', to: [1.3, 0.3], sp: 2.0 }, { mv: 'yil', to: [0.9, -1.3], sp: 1.7, par: true, delay: 0.25 },
        { face: 'ilk', at: 'suk' }, { face: 'yil', at: 'suk', par: true }, { face: 'suk', at: 'ilk', par: true },
      ], { cam: 'wide' }),
      S('Buyurun beyler, hoş geldiniz. Ekmek bitti, yumurta var, sohbet bedava.', { e: 'happy', g: 'present' }),
      I('Şükrü Abi, Necmi Bey\'in veresiye defterine bakabilir miyiz?', { to: 'suk', g: 'explain' }),
      act('Şükrü defteri göğsüne bastırır.', [{ g: 'suk', v: 'cross' }], { cam: 'cu:suk' }),
      S('Defter mahremdir. Defter, mahallenin namusudur.', { e: 'serious', g: 'raise' }),
      Y('Doğru.', { e: 'serious', to: 'suk', g: 'nod' }),
      I('Yılmaz bir dakika sus!', { e: 'angry', to: 'yil', g: 'stop' }),
      Y('Susuyorum. Ama doğru.', { e: 'neutral', to: 'ilk' }),
      I('Çok acil Şükrü Abi. Bir şifre arıyoruz.', { to: 'suk', g: 'explain' }),
      act('Şükrü defteri açar, sayfaları çevirir.', [{ sfx: 'page' }, { g: 'suk', v: 'inspect' }, { wait: 0.4 }, { sfx: 'page' }], { cam: 'cu:suk' }),
      S('Şifre mi? Necmi Bey\'in sayfasında çok şey var. Yumurta, tuz, tava... En altta da bir not var.', { e: 'neutral', g: 'inspect' }),
      I('Ne yazıyor?', { e: 'happy' }),
      S('Söyleyemem. Ama borç devredilebilir.', { e: 'smug' }),
      Y('Ne demek?', { to: 'suk' }),
      S('Necmi Bey\'in borcunu kim kapatırsa, sayfa onun olur. Sayfa onunsa, okur.', { e: 'serious', g: 'explain', to: 'yil' }),
      I('Ne kadar borcu var?', { to: 'suk' }),
      S('Kırk yedi yumurta, üç paket tuz, bir de iki sefer tava kirası.', { e: 'neutral', g: 'count3', to: 'ilk' }),
      I('Tava kirası?', { e: 'surprised' }),
      S('Yumurtasını bende pişirdi. İki sefer.', { e: 'tired' }),
      Y('Benim mutfağımda da pişirdi. Bedava.', { e: 'happy', to: 'suk' }),
      S('Siz komşusunuz. Ben esnafım. Toplam dört yüz on lira.', { e: 'smug', to: 'yil', g: 'raise' }),
      I('Öde.', { to: 'yil', e: 'serious', do: [{ face: 'ilk', at: 'yil' }] }),
      Y('Ben mi?', { to: 'ilk', e: 'surprised', do: [{ face: 'yil', at: 'ilk' }] }),
      I('İnternet senin!', { e: 'angry', g: 'point' }),
      Y('Tamam. Ama bir şartla. Bu borç benim olunca, Necmi Bey bana borçlu olur.', { to: 'suk', g: 'raise', do: [{ face: 'yil', at: 'suk' }] }),
      S('Olur.', { e: 'neutral' }),
      Y('O zaman Necmi Bey\'den bir şey isteyebilirim.', { e: 'happy', g: 'heart' }),
      I('Şifreyi istersin!', { e: 'happy', to: 'yil' }),
      Y('Hayır. Borcunu isterim. Komşudan şifre istenmez, borç istenir. Borç ticarettir.', { e: 'serious', g: 'explain', to: 'ilk' }),
      act('Yılmaz parayı tezgâha bırakır. Yazar kasa çınlar. Şükrü defteri çevirip gösterir.', [
        { mv: 'yil', to: [1.65, -1.1], sp: 0.8 }, { face: 'yil', at: 'suk' }, { g: 'yil', v: 'present' }, { sfx: 'cash' },
        { g: 'suk', v: 'present' }, { mv: 'ilk', to: [1.7, -0.2], sp: 0.8, par: true },
      ], { cam: 'wide' }),
      insert('Veresiye defteri, Necmi Bey\'in sayfası.', {
        kind: 'note', dur: 5.2,
        title: 'NECMİ BEY  (8 numara)',
        lines: ['47 yumurta', '3 pk. tuz', 'tava kirası × 2', '1 gazete (okuyup geri getirdi)', '', 'NOT — internet şifresi:'],
        last: '"Yılmaz Bey\'e sor."',
      }),
      I('"Şifre: Yılmaz Bey\'e sor."', { e: 'surprised', to: 'yil' }),
      Y('Bana mı?', { e: 'surprised', to: 'ilk', cam: 'crash:yil' }),
      I('Sana! Dört yüz on lira verdik, cevap sensin!', { e: 'angry', g: 'flail', to: 'yil' }),
      Y('Ama ben bilmiyorum ki.', { e: 'sad', g: 'shrug' }),
      S('Defter yalan söylemez Yılmaz Bey.', { e: 'serious', to: 'yil', g: 'raise' }),
      Y('Defter söylemiyor zaten. Defter yazıyor.', { e: 'serious', to: 'suk', pause: 0.5 }),
    ],
  },
  // ======================================================================
  {
    id: 'sokak',
    label: 'SAHNE 4',
    heading: 'DIŞ. HUZUR APARTMANI ÖNÜ – SOKAK – AKŞAM',
    set: 'E',
    time: 'evening',
    ambience: 'street',
    cast: {
      ilk: { pos: [-9.5, 0.6], yaw: 90, hold: 'phone' },
      yil: { pos: [-10.3, 0.2], yaw: 90 },
    },
    beats: [
      card('MAÇA 5 DAKİKA', 2.2),
      act('Kaldırımda hızlı adımlarla apartmana doğru yürüyorlar.', [
        { mv: 'ilk', to: [-7.0, 0.6], sp: 1.4 }, { mv: 'yil', to: [-7.8, 0.2], sp: 1.4, par: true },
      ], { cam: 'wide' }),
      I('Düşün Yılmaz. Senin bildiğin, herkesin bildiği, kimsenin söylemediği bir şey.', { e: 'serious', to: 'yil', noface: true, do: [{ mv: 'ilk', to: [-4.6, 0.6], sp: 0.9 }, { mv: 'yil', to: [-5.4, 0.2], sp: 0.9, par: true }] }),
      Y('Ben her şeyi söylerim İlkkan. Söylemediğim bir şey yok.', { e: 'serious', noface: true, do: [{ mv: 'ilk', to: [-3.0, 0.6], sp: 0.8 }, { mv: 'yil', to: [-3.8, 0.2], sp: 0.8, par: true }] }),
      I('Var! Mutlaka var!', { e: 'angry', g: 'flail', noface: true }),
      Y('Bir tane var aslında.', { e: 'neutral', do: [{ face: 'yil', at: 'ilk' }, { face: 'ilk', at: 'yil', par: true }] }),
      I('Ne?', { e: 'happy' }),
      Y('Söylersem söylemiş olurum.', { e: 'serious', g: 'hush' }),
      I('Yılmaz, maç başlıyor!', { e: 'angry', g: 'point' }),
      act('Yılmaz durur. Apartmanın kapısına bakar.', [{ look: 'yil', at: [0, 1.6, -1.6] }, { wait: 1.0 }], { cam: 'cu:yil' }),
      Y('Geçen hafta. Kapıda kaldığımızda. Herkes oradaydı: Necmi Bey, Remzi Efendi, çilingir.', { e: 'sad', look: [0, 1.6, -1.6] }),
      Y('Herkes duydu. Sonra kimse bir daha ağzına almadı.', { e: 'sad', g: 'raise', look: 'ilk' }),
      I('Ne?!', { e: 'surprised', g: 'shrug' }),
      Y('Yedeğin yedeği.', { e: 'serious', cam: 'crash:yil', pause: 0.6 }),
      act('Bir an bakışırlar.', [{ wait: 0.8 }], { cam: 'two' }),
      I('...Koş!', { e: 'scared', g: 'flail' }),
      act('İkisi apartmana koşar.', [
        { mv: 'ilk', to: [0.2, -0.9], sp: 3.4 }, { mv: 'yil', to: [-0.3, -0.9], sp: 3.2, par: true, delay: 0.15 },
        { hide: 'ilk' }, { hide: 'yil', par: true }, { sfx: 'doorClose' }, { wait: 1.0 },
      ], { cam: 'wide' }),
    ],
  },
  // ======================================================================
  {
    id: 'mac',
    label: 'SAHNE 5',
    heading: 'İÇ. YILMAZ\'IN EVİ – SALON – GECE, 20.59',
    set: 'B',
    time: 'night',
    ambience: 'room',
    list: 4,
    flags: { 'B.bowlKey': 1, 'B.rack': 1, 'B.tv': 'nosignal' },
    cast: {
      ilk: { pos: [-5.6, 0.6], yaw: 90, hold: 'phone' },
      yil: { pos: [-6.2, 0.6], yaw: 90, hold: 'remote' },
      nec: { pos: [-6.0, 0.6], yaw: 90, hidden: true, hold: 'key' },
    },
    beats: [
      card('MAÇA 1 DAKİKA', 2.0),
      act('Kilit döner, kapı açılır. İkisi nefes nefese içeri dalar. İlkkan hemen telefonuna yazmaya başlar.', [
        { sfx: 'unlock' }, { wait: 0.4 }, { door: 'B', v: 1, dur: 0.3 }, { sfx: 'doorOpen', par: true },
        { mv: 'ilk', to: [-2.0, 0.7], sp: 3.0 }, { mv: 'yil', to: [-2.9, 0.2], sp: 2.8, par: true, delay: 0.2 },
        { door: 'B', v: 0, dur: 0.5 }, { sfx: 'doorClose', par: true },
        { face: 'ilk', at: TV }, { face: 'yil', at: TV, par: true }, { g: 'ilk', v: 'inspect' },
      ], { cam: 'wide' }),
      insert('"yedeginyedegi" yazar.', { kind: 'pass', dur: 3.4, net: 'Yilmaz_Ev', input: 'yedeginyedegi', ok: true }),
      act('Televizyon bir an düşünür, sonra maç ekrana gelir. Hakem düdüğü.', [
        { vis: 'B.tv', v: 'loading' }, { wait: 1.2 }, { vis: 'B.tv', v: 'match' }, { sfx: 'whistle' }, { sfx: 'crowd', par: true },
        { wait: 1.0 },
      ], { cam: { pos: [2.4, 1.35, 1.3], look: [4.2, 1.1, 1.3] } }),
      I('Bağlandı! Bağlandı Yılmaz!', { e: 'happy', g: 'flail', to: 'yil', do: [{ face: 'ilk', at: 'yil' }] }),
      Y('Kendi internetime misafir olarak bağlandım. Garip bir his.', { e: 'sad', g: 'heart', to: 'ilk' }),
      I('Otur, otur! Başlıyor!', { e: 'happy', g: 'explain' }),
      act('Kanepeye kurulurlar. Gözleri ekranda.', [
        { mv: 'ilk', to: [0.6, -1.55], sp: 1.6 }, { mv: 'yil', to: [-0.5, -1.55], sp: 1.6, par: true },
        { sit: 'ilk', at: [0.6, -2.05], yaw: 0 }, { sit: 'yil', at: [-0.5, -2.05], yaw: 0, par: true },
        { look: 'ilk', at: TV }, { look: 'yil', at: TV, par: true }, { wait: 1.4 },
      ], { cam: 'wide' }),
      act('Kapı çalınır. Cevap beklenmeden kilit döner ve kapı açılır. Elinde anahtarla Necmi Bey içeri girer.', [
        { sfx: 'knock' }, { wait: 0.9 }, { look: 'ilk', at: [-4.5, 1.4, 0.6] }, { look: 'yil', at: [-4.5, 1.4, 0.6], par: true },
        { sfx: 'unlock' }, { wait: 0.4 }, { door: 'B', v: 0.9, dur: 0.6 }, { sfx: 'doorOpen', par: true },
        { show: 'nec' }, { mv: 'nec', to: [-2.6, 0.2], sp: 1.0 }, { face: 'nec', at: 'yil' },
      ], { cam: 'wide' }),
      N('İyi akşamlar! Kapıyı çaldım, açan olmadı. Yedeğin yedeğiyle girdim.', { e: 'happy', g: 'shake_key', to: 'yil' }),
      I('Necmi Bey?!', { e: 'surprised', to: 'nec' }),
      N('Benim internet birden çok yavaşladı. Herhalde biri bağlandı. Ben de maçı burada izleyeyim dedim. Burada internet daha hızlı.', { g: 'explain', to: 'ilk' }),
      I('Modem sizin evinizde!', { e: 'angry', g: 'flail', to: 'nec' }),
      N('Evet. Ama televizyon burada.', { e: 'smug', g: 'point', look: TV }),
      act('Necmi Bey kimseye sormadan berjere kurulur.', [
        { hold: 'nec', v: null }, { door: 'B', v: 0, dur: 0.6 }, { sfx: 'doorClose', par: true },
        { mv: 'nec', to: [1.9, -0.7], sp: 0.9 }, { sit: 'nec', at: [2.3, -1.1], yaw: -63 },
        { look: 'ilk', at: 'nec' }, { look: 'yil', at: 'nec', par: true },
      ], { cam: 'wide' }),
      N('Yılmaz Bey, bir şey isteyeceğim.', { e: 'happy', g: 'raise', to: 'yil' }),
      Y('Buyurun.', { e: 'tired', to: 'nec' }),
      N('Kumanda.', { e: 'smug', g: 'present', cam: 'cu:nec' }),
      act('Yılmaz bir an duraksar. Sonra kalkıp kumandayı uzatır. Necmi Bey kanalı değiştirir.', [
        { wait: 0.6 }, { stand: 'yil' }, { mv: 'yil', to: [1.2, -1.2], sp: 1.0 }, { face: 'yil', at: 'nec' },
        { g: 'yil', v: 'present' }, { hold: 'yil', v: null }, { hold: 'nec', v: 'remote' },
        { mv: 'yil', to: [-0.5, -1.55], sp: 1.0 }, { sit: 'yil', at: [-0.5, -2.05], yaw: 0 },
        { g: 'nec', v: 'point' }, { sfx: 'click', par: true }, { vis: 'B.tv', v: 'fish' }, { sfx: 'bubbles', par: true }, { wait: 0.8 },
      ], { cam: 'wide' }),
      I('Maç!', { e: 'scared', g: 'flail', look: TV }),
      N('Maçın sonucunu yarın gazetede okurum. Balık belgeselinin tekrarı yok.', { e: 'serious', to: 'ilk', g: 'raise' }),
      Y('Misafir ne izlerse o izlenir İlkkan.', { e: 'sad', to: 'ilk' }),
      I('Yılmaz, borç senin! Necmi Bey sana dört yüz on lira borçlu!', { e: 'angry', g: 'explain', to: 'yil' }),
      act('Yılmaz yavaşça Necmi Bey\'e döner.', [{ look: 'yil', at: 'nec' }, { wait: 0.5 }], { cam: 'cu:yil' }),
      Y('Doğru. Necmi Bey, bir şey isteyeceğim.', { e: 'serious', to: 'nec', g: 'raise' }),
      N('Buyurun Yılmaz Bey.', { e: 'happy', to: 'yil' }),
      Y('Borcunuz.', { e: 'serious', cam: 'crash:yil' }),
      N('Tabii. Buyurun: kumanda. Dört yüz on liralık kumanda.', { e: 'smug', g: 'present', to: 'yil' }),
      act('Necmi Bey kumandayı Yılmaz\'a uzatır. Yılmaz kumandaya uzun uzun bakar.', [
        { stand: 'yil' }, { mv: 'yil', to: [1.2, -1.2], sp: 1.0 }, { face: 'yil', at: 'nec' },
        { hold: 'nec', v: null }, { hold: 'yil', v: 'remote' }, { g: 'yil', v: 'inspect' },
      ], { cam: 'two:yil:nec' }),
      Y('...Kabul.', { e: 'serious', to: 'nec' }),
      I('Kabul mü?!', { e: 'surprised', g: 'flail', to: 'yil' }),
      act('Yılmaz maça geri döner. Ekranda skor: 2-1. Maç bitmiş.', [
        { face: 'yil', at: TV }, { g: 'yil', v: 'point' }, { sfx: 'click', par: true },
        { vis: 'B.tv', v: 'match2' }, { sfx: 'whistle' }, { sfx: 'crowd', par: true }, { wait: 0.8 },
      ], { cam: { pos: [2.4, 1.35, 1.3], look: [4.2, 1.1, 1.3] } }),
      I('Maç bitmiş!', { e: 'scared', look: TV }),
      Y('İki bir.', { e: 'neutral', look: TV }),
      I('Kim kazandı?', { e: 'sad', to: 'yil' }),
      Y('Bilmiyorum. Ama ben kumandayı kazandım.', { e: 'smug', g: 'shake_key', to: 'ilk', cam: 'cu:yil', pause: 0.5 }),
      act('Necmi Bey kalkar, hırkasını düzeltir.', [{ stand: 'nec' }, { g: 'nec', v: 'glasses' }], { cam: 'wide' }),
      N('Neyse. Balıkları kaçırdım zaten. İyi geceler.', { e: 'sad', to: 'yil' }),
      act('Necmi Bey çıkar. Kapı kapanır.', [
        { mv: 'nec', to: [-3.6, 0.6], sp: 1.0 }, { door: 'B', v: 0.9, dur: 0.5 }, { sfx: 'doorOpen', par: true },
        { mv: 'nec', to: [-5.8, 0.6], sp: 1.0 }, { hide: 'nec' }, { door: 'B', v: 0, dur: 0.5 }, { sfx: 'doorClose', par: true },
        { face: 'yil', at: 'ilk' }, { stand: 'ilk' }, { face: 'ilk', at: 'yil' },
      ], { cam: 'wide' }),
      Y('Şifreyi değiştiriyorum. Bu sefer kimsenin bilmediği bir şey olacak.', { e: 'serious', g: 'raise', to: 'ilk' }),
      act('Yılmaz İlkkan\'ın telefonunu alır, gözlerini kapatıp bir şeyler yazar.', [
        { hold: 'ilk', v: null }, { hold: 'yil', v: 'phone' }, { g: 'yil', v: 'inspect' },
      ], { cam: 'cu:yil' }),
      insert('Yılmaz yeni şifreyi yazar.', { kind: 'pass', dur: 3.2, net: 'Yilmaz_Ev — yeni şifre', input: '••••••••••••', ok: true, okText: 'Şifre değiştirildi' }),
      I('Ne yazdın?', { to: 'yil' }),
      Y('Bilmiyorum.', { e: 'neutral', to: 'ilk' }),
      I('Nasıl bilmiyorsun?', { e: 'surprised', g: 'shrug' }),
      Y('Kimsenin bilmediği bir şey olsun dedim. Ben de bilmeyeyim dedim. Bakmadan yazdım.', { e: 'smug', g: 'explain' }),
      act('Televizyon donar. Mavi ekran geri gelir.', [{ vis: 'B.tv', v: 'nosignal' }, { sfx: 'error' }, { look: 'ilk', at: TV }, { look: 'yil', at: TV, par: true }, { wait: 1.2 }], { cam: { pos: [2.4, 1.35, 1.3], look: [4.2, 1.1, 1.3] } }),
      I('...İnternet gitti.', { e: 'tired', look: TV }),
      Y('Gitti.', { e: 'neutral', look: TV }),
      N('Yılmaz Bey! İnternet gitti! Şifre ne?', { os: true, e: 'angry', to: 'yil' }),
      act('İkisi birbirine bakar.', [{ look: 'yil', at: 'ilk' }, { look: 'ilk', at: 'yil', par: true }, { wait: 0.6 }], { cam: 'two' }),
      Y('Bunu ona söyleyebilirim aslında.', { e: 'smug', to: 'ilk' }),
      I('Neden?', { e: 'surprised' }),
      Y('Çünkü bilmiyorum. Bilmediğin şeyi söylemek, söylemek sayılmaz.', { e: 'serious', g: 'explain' }),
      I('Bu mantık...', { e: 'tired', g: 'think' }),
      Y('Gibi.', { e: 'smug', cam: 'cu:yil', pause: 1.4 }),
    ],
  },
  // ======================================================================
  { id: 'kapanis', label: 'KAPANIŞ JENERİĞİ', heading: 'KAPANIŞ JENERİĞİ', credits: true, beats: [{ type: 'credits', dur: 14 }] },
];
