// GİBİ — "Yönetim" (hayran bölümü 3)
// Huzur Apartmanı'nda olağanüstü toplantı: gündem aidat, ödünç eşyalar ve
// yönetici seçimi. Motor 2 ile (PBR, 1080p, neural seslendirme) üretilir.
//
// Koordinatlar her setin yerel düzlemindedir (bkz. src/layout.js).

export const meta = {
  series: 'GİBİ',
  title: 'Yönetim',
  tag: 'Hayran Bölümü 3',
  engine: 2,
  tts: 'edge',
  logline:
    'Koridora asılan bir ilan, Huzur Apartmanı\'nı olağanüstü toplantıya çağırır: ' +
    'gündem aidatlar, ödünç alınan eşyalar ve yönetici seçimidir. Üç maddenin üçünün ' +
    'de konusu Yılmaz\'dır. Yılmaz\'ın avukatı olarak toplantıya giren İlkkan ise ' +
    'oturmadığı bir apartmanın yöneticisi olarak çıkar.',
  credits: [
    ['Yılmaz', 'kendisi gibi'], ['İlkkan', 'kendisi gibi (ve bir günlük yönetici)'],
    ['Sevim Hanım', 'eski yönetici'], ['Necmi Bey', 'sekiz numara'], ['Kapıcı Remzi', 'otomat sorumlusu'],
  ],
  outro: ['Aidatınızı ödeyin.', 'Asansör gelirse diye.'],
};

// Neural sesler (Microsoft Edge TTS). rate/pitch: karakterin temel ayarı;
// duygu (e) her replikte bunun üzerine eklenir (bkz. tools/tts_edge.py).
export const cast = {
  yil: { name: 'YILMAZ', voice: { edge: 'tr-TR-AhmetNeural', rate: -6, pitch: -3 } },
  ilk: { name: 'İLKKAN', voice: { edge: 'en-US-BrianMultilingualNeural', rate: 2, pitch: 0 } },
  sev: { name: 'SEVİM HANIM', voice: { edge: 'tr-TR-EmelNeural', rate: 0, pitch: -2 } },
  nec: { name: 'NECMİ BEY', voice: { edge: 'it-IT-GiuseppeMultilingualNeural', rate: -10, pitch: 4 } },
  rem: { name: 'KAPICI REMZİ', voice: { edge: 'de-DE-FlorianMultilingualNeural', rate: -4, pitch: -6 } },
};

const say = (who) => (text, o = {}) => ({ type: 'say', who, text, ...o });
const Y = say('yil');
const I = say('ilk');
const S = say('sev');
const N = say('nec');
const R = say('rem');
const act = (text, ops = [], o = {}) => ({ type: 'act', text, ops, ...o });
const card = (text, dur = 2.6, o = {}) => ({ type: 'card', text, dur, ...o });
const insert = (text, o) => ({ type: 'insert', text, ...o });

export const scenes = [
  // ======================================================================
  {
    id: 'ilan',
    label: 'SOĞUK AÇILIŞ',
    heading: 'İÇ. APARTMAN KORİDORU – SABAH',
    set: 'C',
    time: 'morning',
    ambience: 'hall',
    flags: { 'C.notice': 1 },
    cast: {
      yil: { pos: [-0.3, -1.25], yaw: 180, look: [1.0, 1.5, -2.5] },
      ilk: { pos: [0.55, -1.15], yaw: 190, hold: 'phone', look: [1.0, 1.5, -2.5] },
      sev: { pos: [6.2, 1.2], y: -1.0, yaw: -90, hidden: true, hold: 'clipboard' },
    },
    beats: [
      act('Koridorun duvarına, sayacın yanına yeni bir ilan asılmış. Yılmaz ve İlkkan ilanın önünde durmuş, okuyorlar.', [{ wait: 2.2 }], { cam: 'wide' }),
      insert('İlan.', {
        kind: 'notice', dur: 5.4,
        head: 'HUZUR APARTMANI YÖNETİMİNDEN',
        title: 'OLAĞANÜSTÜ KAT MALİKLERİ TOPLANTISI',
        lines: ['Bu akşam saat 20.00 · 8 numara (Necmi Bey\'in dairesi)', '', 'GÜNDEM', '1. Aidatlar', '2. Ödünç alınan eşyalar', '3. Yönetici seçimi'],
        sign: 'Yönetici Sevim Kaplan',
      }),
      I('Olağanüstü toplantı. Hayırdır?', { e: 'surprised', look: [1.0, 1.5, -2.5] }),
      Y('Olağanüstü toplantı, olağan bir şey olmayacak demek İlkkan.', { e: 'serious', look: 'ilk' }),
      I('Gündemin birinci maddesi aidat. Sen üç aydır aidat ödemiyorsun.', { g: 'point' }),
      Y('Ödemiyorum demeyelim. Ödemeyi bekletiyorum.', { e: 'smug', g: 'raise' }),
      I('Neden bekletiyorsun?'),
      Y('Bir açıklama için. Aidat neye veriliyor, bilmek istiyorum.', { g: 'explain' }),
      I('Apartmanın masraflarına.', { g: 'shrug' }),
      Y('Apartmanın masrafı ne? Asansör yok. Kapıcı kapı açmıyor. Merdiven otomatı on saniyede sönüyor.', { g: 'count3', e: 'serious' }),
      Y('Ben karanlığa para vermem.', { e: 'serious', cam: 'cu:yil' }),
      act('Merdivenlerden topuk sesleri yükselir. Elinde dosyasıyla Sevim Hanım belirir.', [
        { sfx: 'heels' }, { show: 'sev' }, { mv: 'sev', to: [4.0, 0.9], y: 0, sp: 1.2 }, { mv: 'sev', to: [1.9, -0.6], sp: 1.1 },
        { face: 'sev', at: 'yil' }, { face: 'yil', at: 'sev', par: true }, { face: 'ilk', at: 'sev', par: true },
      ], { cam: 'wide' }),
      S('Yılmaz Bey. Günaydın.', { e: 'serious', to: 'yil' }),
      Y('Günaydın Sevim Hanım.', { e: 'neutral', to: 'sev' }),
      S('İlanı okudunuz.', { e: 'serious', g: 'point' }),
      Y('Okuyorum. Henüz bitirmedim.', { e: 'neutral' }),
      S('Bitirmenize gerek yok. Toplantının konusu sizsiniz.', { e: 'smug', g: 'raise' }),
      Y('Gündemin hangi maddesiyim?', { e: 'surprised' }),
      S('Üçünün de.', { e: 'serious', cam: 'cu:sev', pause: 0.4 }),
      act('Sevim Hanım arkasını dönüp merdivenlerden iner. Topuk sesleri uzaklaşır.', [
        { mv: 'sev', to: [4.0, 0.9], sp: 1.2 }, { mv: 'sev', to: [6.2, 1.2], y: -1.0, sp: 1.2 }, { sfx: 'heels', par: true }, { hide: 'sev' },
        { face: 'ilk', at: 'yil' }, { face: 'yil', at: 'ilk', par: true },
      ], { cam: 'wide' }),
      I('Üçünün de mi? Yönetici seçiminde ne işin var?', { e: 'surprised', to: 'yil' }),
      Y('Bilmiyorum. Ama hazırlıklı olmam lazım. İlkkan... Bu akşam bana bir avukat lazım.', { e: 'serious', to: 'ilk' }),
      I('Ben avukat değilim.', { e: 'tired' }),
      Y('Olsun. Toplantıda da kimse gerçekten yönetici değil. Herkes rol yapıyor.', { e: 'smug', g: 'explain', pause: 0.6 }),
    ],
  },
  // ======================================================================
  { id: 'jenerik', label: 'JENERİK', heading: 'JENERİK', title: true, beats: [{ type: 'title', dur: 8.2 }] },
  // ======================================================================
  {
    id: 'prova',
    label: 'SAHNE 1',
    heading: 'İÇ. YILMAZ\'IN EVİ – SALON – ÖĞLEDEN SONRA',
    set: 'B',
    time: 'day',
    ambience: 'room',
    list: 4,
    flags: { 'B.bowlKey': 1, 'B.rack': 1, 'B.tv': 'off', 'B.chairs': 0 },
    cast: {
      yil: { pos: [-1.6, 0.5], yaw: 70, outfit: 'suit' },
      ilk: { pos: [0.4, 0.3], yaw: -110, hold: 'clipboard' },
    },
    beats: [
      act('Yılmaz takım elbisesini giymiş, kravatını düzeltiyor. İlkkan elinde bir dosyayla karşısında.', [{ g: 'yil', v: 'tie' }, { wait: 0.6 }], { cam: 'wide' }),
      I('Prova yapalım. Ben Sevim Hanım\'ım.', { e: 'serious', g: 'explain' }),
      Y('Sen Sevim Hanım olamazsın. Sen benim avukatımsın.', { e: 'serious', g: 'point' }),
      I('Önce karşı tarafı tanımamız lazım. Avukatlık böyle olur.', { e: 'smug', g: 'raise' }),
      Y('Peki. Başla.', { e: 'neutral', g: 'nod' }),
      I('"Yılmaz Bey, aidat."', { e: 'serious', p: 'Sevim Hanım\'ı taklit ederek', g: 'point' }),
      Y('Sevim Hanım, aidat neyin karşılığıdır?', { e: 'smug', g: 'explain' }),
      I('"Apartmanın giderlerinin."', { e: 'serious' }),
      Y('Asansör var mı?', { e: 'smug', g: 'raise' }),
      I('"Yok."'),
      Y('O zaman asansör payını düşüyorum.', { e: 'happy', g: 'present' }),
      I('"Asansör payı zaten yok Yılmaz Bey. Asansör olmadığı için."', { e: 'smug', g: 'shrug' }),
      act('Yılmaz bir an donar.', [{ g: 'yil', v: 'freeze' }, { wait: 0.4 }], { cam: 'cu:yil' }),
      Y('...Yoksa düşemem. Bu çok kötü bir hamle oldu.', { e: 'sad' }),
      I('Gördün mü? Karşı taraf güçlü.', { e: 'serious', g: 'point' }),
      Y('Kapıcı?', { e: 'serious' }),
      I('"Kapıcı kapıyı bekler, açmaz. Bunu siz söylediniz."', { e: 'smug' }),
      Y('Ben söyledim ama o kabul etti. Kabul eden razıdır. Razı olana para verilmez.', { e: 'serious', g: 'explain' }),
      I('Bu ne demek?', { e: 'surprised', g: 'shrug' }),
      Y('Bilmiyorum. Ama güçlü durdu.', { e: 'smug', g: 'hips' }),
      I('Otomat?', { e: 'tired' }),
      Y('On saniyede sönüyor. Ben beşinci kata yirmi iki saniyede çıkıyorum. On iki saniye karanlıkta yürüyorum.', { g: 'count3', e: 'serious' }),
      Y('On iki saniyelik ışığın parasını kesiyorum.', { e: 'serious', g: 'stop' }),
      I('Kaç lira tutar?'),
      act('Yılmaz düşünür.', [{ g: 'yil', v: 'think' }], { cam: 'cu:yil' }),
      Y('Hesaplamadım. Ama prensip.', { e: 'serious', g: 'raise' }),
      I('Prensipten para çıkmaz Yılmaz.', { e: 'tired', g: 'shrug' }),
      I('Peki, ikinci madde. Ödünç alınan eşyalar. Bu seni değil, Necmi Bey\'i ilgilendiriyor.', { e: 'neutral', g: 'explain' }),
      Y('Beni de ilgilendiriyor. Ben ödünç veren tarafım. Modemim, matkabım, tavam... Necmi Bey\'in evi benim eşyalarımla dolu.', { e: 'sad', g: 'count3' }),
      I('O zaman toplantıda eşyalarını geri istersin.', { g: 'point' }),
      Y('İstemem. Toplantı Necmi Bey\'in evinde. Misafirken ev sahibinden eşya istenmez.', { e: 'serious', g: 'stop' }),
      I('Toplantıyı neden onun evinde yapıyorlar?'),
      Y('Çünkü yönetim odası yok. Yönetim odası, Necmi Bey\'in salonu. Sandalyeler de benim sandalyelerim.', { e: 'sad', g: 'explain', look: [0.0, 0.6, -1.0] }),
      I('Senin sandalyelerin mi?', { e: 'surprised' }),
      Y('Dört sandalye. Perşembe günü istedi. "Toplantı var" dedi. Toplantıyı ben öğrenmeden sandalyelerim öğrendi.', { e: 'sad', g: 'count3' }),
      I('Üçüncü madde. Yönetici seçimi.', { e: 'serious' }),
      Y('İşte o madde beni korkutuyor.', { e: 'scared', cam: 'cu:yil' }),
      I('Neden?'),
      Y('Sevim Hanım istifa ediyorsa yerine biri seçilecek. Beni seçerlerse borcum yönetime olur, yönetim de ben olurum. Kendime borçlu olurum.', { e: 'scared', g: 'explain' }),
      I('Bu iyi bir şey değil mi?', { e: 'surprised', g: 'shrug' }),
      Y('Kendime borcumu ödemezsem, kendimi dava ederim İlkkan. Bu çok yorucu.', { e: 'tired', g: 'facepalm', pause: 0.6 }),
    ],
  },
  // ======================================================================
  {
    id: 'toplanti',
    label: 'SAHNE 2',
    heading: 'İÇ. NECMİ BEY\'İN EVİ – SALON – GECE, 20.00',
    set: 'G',
    time: 'night',
    ambience: 'clock',
    cast: {
      sev: { pos: [0.0, -1.95], yaw: 0, sit: true, hold: 'clipboard' },
      nec: { pos: [2.55, -1.1], yaw: -70, sit: true },
      yil: { pos: [-1.0, -0.65], yaw: 90, sit: true, outfit: 'suit' },
      ilk: { pos: [1.0, -0.65], yaw: -90, sit: true, hold: 'clipboard' },
      rem: { pos: [-3.1, -1.6], yaw: 50, hold: 'notebook' },
    },
    beats: [
      card('20.00', 2.0),
      act('Necmi Bey\'in salonu. Her eşyanın üstünde küçük sarı bir kâğıt: "Yılmaz Bey". Masanın başında Sevim Hanım, önünde bir masa zili. Duvardaki saat tıkırdıyor.', [
        { wait: 2.4 },
      ], { cam: 'wide' }),
      act('Sevim Hanım zile basar.', [{ g: 'sev', v: 'bell' }, { sfx: 'deskbell', time: 0.25 }], { cam: 'cu:sev' }),
      S('Toplantıyı açıyorum. Yoklama. Necmi Bey.', { e: 'serious', to: 'nec' }),
      N('Buradayım. Evim burası.', { e: 'happy', to: 'sev' }),
      S('Remzi Efendi.', { to: 'rem' }),
      R('Buradayım. Tutanağı ben tutuyorum.', { e: 'serious', g: 'raise', to: 'sev' }),
      S('Yılmaz Bey.', { to: 'yil' }),
      Y('Buradayım. Sandalyem de burada.', { e: 'serious', to: 'sev' }),
      S('Bu beyefendi?', { e: 'surprised', to: 'ilk', g: 'point' }),
      I('Avukat.', { e: 'serious', to: 'sev' }),
      S('Kimin avukatı?', { to: 'ilk' }),
      I('Yılmaz\'ın.', { g: 'present', to: 'sev' }),
      S('Kat maliki misiniz?'),
      I('Değilim.'),
      S('O zaman oy hakkınız yok.', { e: 'smug' }),
      I('Oy kullanmaya gelmedim. Savunmaya geldim.', { e: 'serious', g: 'raise' }),
      S('Gündemin birinci maddesi: aidatlar. Yılmaz Bey, üç aydır aidat ödemiyorsunuz.', { e: 'serious', to: 'yil', g: 'point' }),
      Y('Ödemiyorum demeyelim. Bekletiyorum.', { e: 'smug', to: 'sev' }),
      S('Neyi bekliyorsunuz?', { e: 'angry' }),
      Y('Asansörü.', { e: 'serious', cam: 'cu:yil' }),
      S('Asansör yok Yılmaz Bey.', { e: 'angry' }),
      Y('Gelene kadar bekleyeceğim.', { e: 'serious' }),
      act('Remzi tutanağa yazar.', [{ g: 'rem', v: 'write' }], { cam: 'cu:rem' }),
      R('"Yılmaz Bey asansörü bekliyor."', { e: 'serious', g: 'write', p: 'yazarken' }),
      I('Müvekkilim ayrıca merdiven otomatının on saniyede söndüğünü ve on iki saniye karanlıkta yürüdüğünü beyan ediyor.', { e: 'serious', g: 'explain', to: 'sev' }),
      S('Bunun aidatla ne ilgisi var?', { e: 'angry', to: 'ilk' }),
      I('Ne ilgisi var?', { to: 'yil', p: 'Yılmaz\'a, fısıltıyla' }),
      Y('Karanlıkta yürüyen insan, aidatı da karanlıkta öder. Yani ödemez.', { e: 'serious', g: 'explain', to: 'sev' }),
      S('Remzi Efendi, otomat kaç saniye?', { e: 'serious', to: 'rem' }),
      R('On saniye Sevim Hanım. Ama ben bekliyorum, sönünce tekrar basıyorum.', { e: 'neutral', to: 'sev' }),
      Y('İşte! Kapıcı kapıyı açmıyor ama otomata basıyor. Ben otomata basana para veririm.', { e: 'happy', g: 'point', to: 'sev' }),
      S('Kime?', { e: 'surprised' }),
      Y('Remzi Efendi\'ye. Doğrudan. Yönetime değil.', { e: 'smug', g: 'present' }),
      R('Sağ olun Yılmaz Bey.', { e: 'happy', to: 'yil' }),
      S('Olmaz! Aidat yönetime ödenir!', { e: 'angry', g: 'bell' }),
      N('Bir şey söyleyebilir miyim?', { e: 'neutral', g: 'raise', to: 'sev' }),
      S('Söyleyin Necmi Bey.', { e: 'tired', to: 'nec' }),
      N('Bir şey isteyeceğim.', { e: 'happy', cam: 'cu:nec' }),
      act('Herkes Necmi Bey\'e bakar. Saat tıkırdar.', [{ wait: 1.4 }], { cam: 'wide' }),
      S('İkinci maddeye geçiyorum. Ödünç alınan eşyalar.', { e: 'serious', g: 'raise' }),
      S('Necmi Bey, apartmanda ödünç aldığınız eşyaların listesini çıkardım.', { e: 'serious', to: 'nec' }),
      insert('Sevim Hanım\'ın listesi.', {
        kind: 'note', dur: 5.0, paper: 'white',
        title: 'NECMİ BEY — ÖDÜNÇ ALINANLAR',
        lines: ['1 modem', '1 matkap', '1 tava', '4 sandalye', '1 kumanda', '1 merdiven otomatı sırası (!)'],
        last: 'Hepsinin sahibi: Yılmaz Bey',
      }),
      N('Kumandayı geri verdim. Dört yüz on liraya.', { e: 'smug', to: 'sev' }),
      Y('Doğru.', { e: 'neutral', g: 'nod' }),
      S('Yılmaz Bey, eşyalarınızı geri istiyor musunuz?', { to: 'yil' }),
      Y('Misafirken ev sahibinden eşya istenmez Sevim Hanım.', { e: 'serious', g: 'stop' }),
      S('Toplantıdasınız! Misafir değilsiniz!', { e: 'angry', g: 'bell' }),
      Y('Toplantı Necmi Bey\'in evinde. Toplantı misafirdir.', { e: 'serious', g: 'raise' }),
      I('Bu doğru. Toplantının kendi evi yok.', { e: 'serious', g: 'explain', to: 'sev' }),
      act('Sevim Hanım derin bir nefes alır, dosyasını kapatır.', [{ g: 'sev', v: 'sigh' }], { cam: 'cu:sev' }),
      S('Peki. Üçüncü madde. Yönetici seçimi. Ben istifa ediyorum.', { e: 'tired' }),
      R('Neden Sevim Hanım?', { e: 'surprised', to: 'sev' }),
      S('Çünkü bu apartmanda kimse aidat ödemiyor, herkes bir şey istiyor ve otomat on saniye.', { e: 'tired', g: 'count3' }),
      N('Doğru söylüyor.', { e: 'serious', g: 'nod' }),
      S('Aday var mı?', { e: 'serious', g: 'raise' }),
      act('Sessizlik. Herkes önüne bakar.', [
        { look: 'yil', at: [0, 0.75, -0.65] }, { look: 'nec', at: [1.5, 0.3, -0.6], par: true }, { look: 'rem', at: [-2.6, 1.0, -1.0], par: true },
        { look: 'ilk', at: [0.5, 0.75, -0.65], par: true }, { wait: 1.8 },
      ], { cam: 'wide' }),
      Y('İlkkan.', { e: 'serious', cam: 'cu:yil' }),
      I('Ne?!', { e: 'scared', to: 'yil', cam: 'crash:ilk' }),
      S('Beyefendi kat maliki değil.', { e: 'serious', to: 'yil' }),
      Y('Yönetmelikte "kat maliki olmayan yönetici olamaz" diye bir madde var mı?', { e: 'smug', to: 'sev' }),
      act('Sevim Hanım dosyasındaki yönetmeliği karıştırır.', [{ g: 'sev', v: 'inspect' }, { sfx: 'page' }, { wait: 0.6 }, { sfx: 'page' }], { cam: 'cu:sev' }),
      S('...Yok.', { e: 'surprised' }),
      Y('O zaman olur.', { e: 'smug', g: 'present' }),
      I('Yılmaz, ben bu apartmanda oturmuyorum!', { e: 'angry', g: 'flail', to: 'yil' }),
      Y('İşte bu yüzden en tarafsız aday sensin. Kimseye borcun yok, kimseden bir şey istemiyorsun, otomatın kaç saniye olduğu seni hiç ilgilendirmiyor.', { e: 'serious', g: 'explain', to: 'ilk' }),
      N('Ben İlkkan Bey\'e oy veriyorum. Bana hiçbir şey vermedi ama hiçbir şey de istemedi.', { e: 'happy', g: 'raise' }),
      R('Ben de. İlkkan Bey, otomata siz de basar mısınız?', { e: 'neutral', to: 'ilk' }),
      I('Basmam!', { e: 'angry', to: 'rem' }),
      R('Dürüst adam. Oyum İlkkan Bey\'e.', { e: 'happy', g: 'raise' }),
      S('Yılmaz Bey?', { to: 'yil' }),
      Y('Ben de İlkkan\'a veriyorum.', { e: 'happy', g: 'raise' }),
      act('Sevim Hanım iç çeker ve zile basar.', [{ g: 'sev', v: 'bell' }, { sfx: 'deskbell', time: 0.25 }], { cam: 'cu:sev' }),
      S('Oy birliğiyle... yeni yöneticimiz İlkkan Bey. Hayırlı olsun.', { e: 'tired', to: 'ilk' }),
      I('Benim oy hakkım bile yok!', { e: 'scared', g: 'flail' }),
      S('Yöneticinin oy hakkına ihtiyacı yok. Yönetici yönetir.', { e: 'smug', g: 'present', to: 'ilk' }),
      act('Sevim Hanım dosyayı masanın üzerinden İlkkan\'a uzatır. İlkkan dosyaya, sonra Yılmaz\'a bakar.', [
        { hold: 'sev', v: null }, { look: 'ilk', at: 'yil' }, { wait: 1.0 },
      ], { cam: 'two:ilk:yil' }),
      Y('Tebrik ederim İlkkan. Şimdi bir şey isteyeceğim.', { e: 'happy', to: 'ilk' }),
      I('Ne?', { e: 'tired' }),
      Y('Aidatımı bekletmek istiyorum.', { e: 'smug', cam: 'cu:yil', pause: 0.6 }),
    ],
  },
  // ======================================================================
  {
    id: 'ilkgun',
    label: 'SAHNE 3',
    heading: 'İÇ. APARTMAN GİRİŞİ – ERTESİ SABAH',
    set: 'D',
    time: 'morning',
    ambience: 'hall',
    cast: {
      ilk: { pos: [0.9, -1.5], yaw: 10, hold: 'clipboard' },
      rem: { pos: [2.6, -2.15], yaw: 0, sit: true, hold: 'tea' },
      nec: { pos: [-0.6, 0.6], yaw: 160 },
      sev: { pos: [-1.6, 1.2], yaw: 150, hold: 'clipboard' },
      yil: { pos: [-3.85, -3.4], y: 1.85, yaw: 180, outfit: 'normal', hidden: true },
    },
    beats: [
      card('Ertesi sabah. Yönetimin ilk günü.', 2.8),
      act('İlkkan, kapıcı masasının yanına bir sandalye çekmiş, elinde yönetim dosyası. Önünde küçük bir kuyruk: Necmi Bey ve Sevim Hanım.', [
        { wait: 1.2 }, { mv: 'nec', to: [0.0, -0.4], sp: 0.7 }, { face: 'nec', at: 'ilk' }, { face: 'ilk', at: 'nec', par: true },
      ], { cam: 'wide' }),
      N('İlkkan Bey, yönetime bir talebim var.', { e: 'happy', g: 'raise' }),
      I('Buyurun Necmi Bey.', { e: 'serious' }),
      N('Bir şey isteyeceğim.'),
      I('Ne istiyorsunuz?', { e: 'tired' }),
      N('Yönetimin matkabı var mı?', { e: 'neutral', g: 'explain' }),
      I('Yönetimin hiçbir şeyi yok. Yönetim benim. Benim de matkabım yok.', { e: 'serious', g: 'shrug' }),
      N('Yılmaz Bey\'in var.', { e: 'smug' }),
      I('O matkap zaten sizde!', { e: 'angry', g: 'point' }),
      N('Evet ama yönetimden istersem resmî olur.', { e: 'serious', g: 'raise', pause: 0.3 }),
      act('Remzi masasından kalkar.', [{ stand: 'rem' }, { hold: 'rem', v: null }, { mv: 'rem', to: [1.9, -0.6], sp: 0.8 }, { face: 'rem', at: 'ilk' }, { face: 'ilk', at: 'rem', par: true }], { cam: 'wide' }),
      R('İlkkan Bey, maaşıma zam istiyorum. Otomata basmaktan parmağım nasır oldu.', { e: 'sad', g: 'raise' }),
      I('Remzi Abi, kasada para yok. Kimse aidat ödemiyor.', { e: 'tired', g: 'shrug' }),
      R('Yılmaz Bey ödemiyor.', { e: 'neutral' }),
      I('Yılmaz ödemiyor çünkü... asansörü bekliyor.', { e: 'tired', pause: 0.2 }),
      act('Sevim Hanım öne çıkar.', [{ mv: 'sev', to: [-0.4, 0.3], sp: 0.9 }, { face: 'sev', at: 'ilk' }, { face: 'ilk', at: 'sev', par: true }], { cam: 'wide' }),
      S('İlkkan Bey, kat maliki olarak şikâyetim var. Merdiven otomatı on saniyede sönüyor.', { e: 'serious', g: 'point' }),
      I('Siz yönetici değil miydiniz? Sizin zamanınızda da on saniyeydi!', { e: 'angry', g: 'flail' }),
      S('O zaman yöneticiydim, şikâyet edemezdim. Şimdi kat malikiyim. Şikâyet hakkım var.', { e: 'smug', g: 'raise' }),
      I('Tamam! Otomatı yirmi beş saniye yapıyorum!', { e: 'angry', g: 'flail' }),
      R('Elektrik faturası artar.', { e: 'neutral', to: 'ilk' }),
      I('Aidattan ödenir!', { e: 'angry', to: 'rem' }),
      S('Aidatı kimse ödemiyor.', { e: 'smug', to: 'ilk' }),
      act('İlkkan merdivenlere doğru bağırır.', [{ face: 'ilk', at: [-3.85, -2.0] }, { look: 'ilk', at: [-3.85, 1.6, -2.8] }], { cam: 'cu:ilk' }),
      I('Yılmaz!', { e: 'angry', g: 'flail', look: [-3.85, 1.6, -2.8], cam: 'crash:ilk' }),
      act('Yılmaz, takım elbisesini çıkarmış, sakin adımlarla merdivenlerden iner.', [
        { show: 'yil' }, { mv: 'yil', to: [-3.85, -0.8], y: 0, sp: 0.9 }, { mv: 'yil', to: [-1.6, -0.9], sp: 0.9 },
        { face: 'yil', at: 'ilk' }, { look: 'nec', at: 'yil', par: true }, { look: 'sev', at: 'yil', par: true }, { look: 'rem', at: 'yil', par: true },
      ], { cam: 'wide' }),
      Y('Günaydın Sayın Yönetici.', { e: 'happy', to: 'ilk', g: 'wave' }),
      I('Yılmaz, aidatını öde!', { e: 'angry', g: 'point', to: 'yil', do: [{ face: 'ilk', at: 'yil' }] }),
      Y('Ödemek istiyorum aslında.', { e: 'neutral' }),
      I('Gerçekten mi?', { e: 'surprised' }),
      Y('Ama bir şartla. Yönetim bana yazılı bir belge versin: "Asansör yoktur. Kapıcı kapı açmaz. Otomat on saniyedir. Bunlara rağmen Yılmaz Bey aidat öder."', { e: 'serious', g: 'count3' }),
      I('Bu belge neye yarayacak?', { e: 'surprised', g: 'shrug' }),
      Y('Çerçeveletip acil durum listesinin yanına asacağım. İnsanın neye para verdiğini bilmesi, acil durumdur.', { e: 'serious', g: 'heart' }),
      act('İlkkan dosyadan bir sayfa yazar, imzalar, koparıp uzatır. Yılmaz cebinden bir zarf çıkarır.', [
        { g: 'ilk', v: 'write' }, { sfx: 'page' }, { g: 'ilk', v: 'present' }, { hold: 'yil', v: 'envelope' }, { g: 'yil', v: 'present' },
      ], { cam: 'two:yil:ilk' }),
      Y('Üç aylık aidat. Bir de bir aylık peşin.', { e: 'smug', g: 'present' }),
      S('Peşin mi?!', { e: 'surprised', g: 'jump' }),
      R('Peşin mi?!', { e: 'surprised', g: 'jump' }),
      N('Peşin mi?', { e: 'surprised' }),
      Y('Gelecek ay asansör gelirse diye.', { e: 'serious', cam: 'cu:yil' }),
      act('İlkkan zarfı alır. Herkese bakar.', [{ hold: 'yil', v: null }, { hold: 'ilk', v: 'envelope' }, { wait: 0.8 }], { cam: 'cu:ilk' }),
      I('Kasada para var. Remzi Abi, otomatı yirmi beş saniye yap.', { e: 'happy', to: 'rem' }),
      R('Hemen İlkkan Bey!', { e: 'happy', g: 'wave' }),
      N('İlkkan Bey, bir şey isteyeceğim.', { e: 'happy', to: 'ilk' }),
      I('Ne?', { e: 'tired', to: 'nec' }),
      N('Bu para ödünç verilir mi?', { e: 'smug', g: 'present' }),
      act('Uzun bir sessizlik. İlkkan dosyayı kapatır.', [{ wait: 1.2 }, { g: 'ilk', v: 'sigh' }], { cam: 'cu:ilk' }),
      I('İstifa ediyorum.', { e: 'tired', pause: 0.6 }),
    ],
  },
  // ======================================================================
  {
    id: 'son',
    label: 'SON',
    heading: 'İÇ. YILMAZ\'IN EVİ – SALON – AKŞAM',
    set: 'B',
    time: 'night',
    ambience: 'room',
    list: 4,
    flags: { 'B.bowlKey': 1, 'B.rack': 1, 'B.tv': 'off', 'B.belge': 1 },
    cast: {
      ilk: { pos: [0.6, -2.05], yaw: 0, sit: true },
      yil: { pos: [-1.3, -2.2], yaw: 180, look: [-1.3, 1.7, -3.0] },
    },
    beats: [
      act('Akşam. Yılmaz, çerçeveletilmiş belgeyi acil durum listesinin yanına asıyor. İlkkan kanepeye gömülmüş.', [
        { g: 'yil', v: 'present' }, { wait: 0.6 }, { sfx: 'click' }, { mv: 'yil', to: [-1.3, -1.4], sp: 0.6 }, { face: 'yil', at: 'ilk' },
      ], { cam: 'wide' }),
      I('Bir günlük yöneticilik. Hayatımın en uzun günüydü.', { e: 'tired', to: 'yil' }),
      Y('Olsun. Tarihe geçtin. Huzur Apartmanı\'nın ilk "orada oturmayan" yöneticisi.', { e: 'happy', g: 'present' }),
      I('Yeni yönetici kim oldu?'),
      Y('Necmi Bey.', { e: 'neutral' }),
      I('Necmi Bey mi?!', { e: 'surprised' }),
      Y('Oy birliğiyle. Sevim Hanım\'ın önerisi. "Yönetici olursa artık kendinden istemesi gerekir" dedi.', { e: 'serious', g: 'explain' }),
      I('Mantıklı. İlk icraatı ne?', { e: 'neutral' }),
      act('Kapı çalınır.', [{ sfx: 'knock' }, { look: 'ilk', at: [-4.5, 1.4, 0.6] }, { look: 'yil', at: [-4.5, 1.4, 0.6], par: true }, { wait: 0.6 }], { cam: 'wide' }),
      N('Yılmaz Bey! Yönetim adına bir şey isteyeceğim!', { os: true, e: 'happy', to: 'yil' }),
      act('İkisi birbirine bakar.', [{ look: 'yil', at: 'ilk' }, { look: 'ilk', at: 'yil', par: true }, { wait: 0.7 }], { cam: 'two' }),
      Y('Sandalyelerimi getirsin önce. Toplantı bitti.', { e: 'serious', look: [-4.5, 1.4, 0.6] }),
      N('Sandalyeler yönetimin demirbaşına geçti!', { os: true, e: 'serious', to: 'yil' }),
      I('Senin sandalyelerin apartmanın oldu.', { e: 'smug', to: 'yil' }),
      Y('Olsun. Artık apartmanın da oturacak bir yeri var.', { e: 'sad', g: 'heart' }),
      Y('Ev sahibi olmak böyle bir şey İlkkan. Bazen sandalye senindir, bazen sen sandalyenin.', { e: 'serious', g: 'explain', cam: 'cu:yil' }),
      I('Bu çok derin bir söz gibi.', { e: 'neutral' }),
      Y('Gibi değil. Derin.', { e: 'serious', cam: 'cu:yil', pause: 0.6 }),
      N('Bir de modem!', { os: true, e: 'happy', to: 'yil', pause: 1.4 }),
    ],
  },
  // ======================================================================
  { id: 'kapanis', label: 'KAPANIŞ JENERİĞİ', heading: 'KAPANIŞ JENERİĞİ', credits: true, beats: [{ type: 'credits', dur: 15 }] },
];
